$ $TOG: dtcm.msg /main/12 1999/09/20 10:35:18 mgreess $
$quote "

$set 1

1 "dtcm: Nemo accipiens  in repetitionis epistula.\n"

2 "Repetitio - %s"

3 "pm"

4 "am"

5 "pm"

6 "am"

7 "\n\n\
\t** Constitutum (libelli) **\n\n\
\tDie:\t%s\n\
\tInitium:\t%s\n\
\tFinis:\t%s\n\
\tRes:\t%s"

8 "Ab %2d:%02d"

9 "am"

10 "pm"

11 "am"

12 "pm"

13 "Ab %02d%02d usque %02d%02d"

16 "Delere libellus absentem aliquis non potest."

17 "Seligere nominem delendum."

20 "Dies vitiosus in regione Usque."

21 "Mutare indicem..."

22 "Optiones indicis Perlustrare"

23 "Hebdomas ant."

24 "Hoc hebdomas"

25 "Hebdomas post."

26 "Mensis ant."

27 "Hoc mensis"

28 "Usque:"

29 "Conjicere..."

30 "Epistola..."

31 "Libellus propositus"

32 "Libelli propositi"

33 "Die"

34 "Hebdomas"

35 "Mensis"

36 "Anno"

37 "Circulus temporalis..."

38 "Index constitutorum..."

40 "Aspicere"

41 "Quaerere..."

42 "Quaerere diei..."

65 "Scapus"

68 "Exscr. conspectum in effectu"

69 "Exscribere..."

72 "Optiones..."

73 "Exire"

74 "Constituta..."

76 "Redigere"

77 "Adjumentum"

79 "Pensa..."

80 "Relatio..."

82 "Adjumentum adjumenti..."

84 "Aspic. alter libellus..."

85 "Compar. libelli..."

86 "Editor indicis..."

87 "Perlustrare"

88 "Hodie"

89 "in quit_handler\n"

90 "Error accidit dum apertione scapi libelli."

91 "rpc.cmsd non respondit pro nomine usoris tuo.\n\
Verifica processus inetd adesse et linea \n\
cum rpc.cmsd in scapi inetd.conf valida esse."

92 "Nomine usoris"

93 "Hospes"

94 "Error - Libellus"

95 "Exsegui"

96 "Nullus scapus libelli pro"

97 "Nullus scapus libelli pro"

98 "Error - Libellus"

99 "Exsegui"

100 "SINE NOMEN"

101 "rpc.cmsd non respondit pro"

102 "rpc.cmsd non respondit pro nomine usoris tuo.\n\
Verifica processus inetd adesse et linea\n\
cum rpc.cmsd in scapo inetd.conf valida esse."

103 "Nomen usoris"

104 "Hospes"

105 "Error - Libellus"

106 "Exsegui"

107 "%s: NIHIL NOMEN"

108 "Nihil locus libelli indicatus ut"

109 "Nihil locus indicatus est. Adde nominem hospitis in zona Conspectus initiis \n\
libelli (optio Proponere parametri indicis Insignes). Si \n\
 coepisti DTCM cum optio -c, verifica quod indicares nominem hospitis."

110 "Error - Libellus"

111 "Exsegui"

112 "Versiones DTCM et rpc.cmsd dissimiles sunt."

113 "Libellus"

114 "Januarius"

115 "Februarius"

116 "Martius"

117 "Aprilis"

118 "Maius"

119 "Junius"

120 "Julius"

121 "Augustus"

122 "September"

123 "October"

124 "November"

125 "December"

126 "Jan"

127 "Feb"

128 "Mar"

129 "Apr"

130 "Mai"

131 "Jun"

132 "Jul"

133 "Aug"

134 "Sep"

135 "Oct"

136 "Nov"

137 "Dec"

138 "Sol"

139 "Lun"

140 "Mar"

141 "Mer"

142 "Jov"

143 "Ven"

144 "Sat"

145 "Sol"

146 "Dies Solis"

147 "Dies Lunae"

148 "Dies Marti"

149 "Dies Mercurii"

150 "Dies Jovis"

151 "Dies Veneris"

152 "Dies Saturni"

153 "Dies Solis"

154 "S"

155 "L"

156 "M"

157 "Me"

158 "J"

159 "V"

160 "Sa"

161 "S"

162 "S"

163 "L"

164 "M"

165 "Me"

166 "J"

167 "V"

168 "Sa"

169 "S"

170 "SOL"

171 "LUN"

172 "MAR"

173 "MER"

174 "JOV"

175 "VEN"

176 "SAT"

177 "SOL"

178 "%s aspicio in effectu est."

186 "Versiones DTCM et rpc.cmsd dissimiles sunt."

187 "Syntaxe:\n\
\tdtcm_delete [-c libellus] [-d <mm/dd/aa>] [-v conspectus]\n"

188 "\n\
Aperire libellum %s non potest.\n"

189 "IGNOTUS"

190 "Rem sublatam (numero) ? "

191 "Syntaxis:\n\
\tdtcm_insert [ -c libellus ] [-d <mm/dd/aa>] [ -v conspectus ]\n"

192 "                   [-w litterarum series] [-s <HH:MMam/pm>] [-e <HH:MMam/pm>]\n"

193 "Indice percontationes addendae constituti.\n\
Valores absentem aliquid vides inter parenthesis.\n"

194 "Libellus (%s): "

195 "Dies (%s): "

196 "Initium (%s): "

197 "Indicavisti vitiosam horam ; emenda eam.\n"

198 "Finis (%s): "

199 "Finis (%s): "

200 "Semel"

201 "Iterare (%s): "

202 "Semel"

203 "nullus absentem aliquid"

204 "Ad (%s): "

205 "Commentaria (5 lineas maximum, ^D ad interrumpendum):\n"

206 "\n\
Aperire libellum %s non potest.\n"

207 "Syntaxis:\n\
\tdtcm_lookup [ -c libellus ][ -d <mm/dd/aa> ] [ -v conspectus ]\n"

208 "\n\
 Aperire libellum \"%s\" non potest.\n"

209 "IGNOTUS"

210 "constitutum preameditabitur in vertens libello.\n\
Confirmasne hoc operem ?"

211 "Conjicere in"

212 "Conjicere constitutum"

214 "Constitutum praemeditatum: %s\n"

218 "DIEM indicatum vitiosum est."

219 "Hora INITII indicata vitiosa est."

220 "Hora FINIS indicata vitiosa est."

221 "Zona INITII vacua est aut deest."

222 "Zona FINIS vacua est aut deest."

223 "Zona COMMENTARIA vacua est aut deest."

224 "Zonae ITERARE et AD alienae sunt."

225 "Constitutum praemeditatum rescissum est."

226 "Error internus cum praemeditatione constituti."

227 "Constitutum praemeditatum rescissum est."

228 "Constitutum Onerare"

229 "Exsegui"

230 "Labi constitutum fac"

231 "Selige constitutum et deinde id labi fac."

232 "Exsegui"

234 "Labi constitutum fac"

235 "Exsegui"

236 "ConstututumLibelli"

237 "XCreateBitmapFromData() n'a pas abouti pour le bitmap.\n"

238 "XCreateBitmapFromData() n'a pas abouti pour le masque.\n"

239 "DragStart a retourné une valeur NULLE.\n"

242 "am"

243 "pm"

244 "%s 3:41am"

245 "am"

246 "pm"

247 "Hora finis ejus constitutum ante\n\
hora initii est. Visne praemeditare eam\n\
postridie ?"

248 "Constitutum Conjicere"

250 "Cras"

251 "Auctor"

252 "Tollere constitutum"

253 "Seligere constitutum, postea tollere."

254 "Exsegui"

255 "Tollere constitutum"

256 "Error internus accidit dum selectione\n\
constituti. Id rescissum non est."

257 "Exsegui"

258 "Constitutum mutare"

259 "Constitutum seligere, postea mutare."

260 "Exsegui"

261 "Constitutum mutare"

262 "Error internus accidit dum selectione\n\
constituti. Id mutatum non est."

263 "Exsegui"

267 "Constitutum mutare"

268 "Hoc constitutum partem seriei recurentis est.\n\
Confirmasne mutationem...?"

270 "Hoc constitutum solum"

271 "Sequentes"

272 "Omnis"

273 "Tollere constitutum"

274 "Hoc constitutum partem seriei recurrentis est.\n\
Confirmasne sublationem...?"

276 "Hoc constitutum solum"

277 "Sequentes"

278 "Omnis"

279 "Editorium constituti"

280 "Aspic. index constitutorum"

281 "Index constitutum non continet."

282 "Exsegui"

283 "Libellus - Programma quaero"

284 "Quaerere:"

285 "Quaerere"

289 "Adjumentum"

290 "Induce litterarum series quaerendae."

291 "Constitutum invenire non potest."

292 "%d casus(i) inventus(i)."

293 "Die:"

294 "Usque"

296 "Adjumentum"

297 "Indica diem."

298 "%s aspicio in effectu est."

299 "Dies vitiosus."

300 "Auctor"

304 "Cursus..."

305 "Inserere constitutum"

306 "Seligere libellum, postea Inserere."

307 "Exsegui"

308 "Tollere constitutum"

309 "Seligere constitutum, postea Tollere."

310 "Exsegui"

311 "Tollere constitutum"

312 "Error internus accidit dum selectione \n\
constituti. Id rescissum non est."

313 "Exsegui"

314 "Tollere conventum"

315 "Seligere libellum, postea Tollere."

316 "Exsegui"

317 "Tollere constitutum"

318 "Hoc constitutum partem seriei recurrentis est.\n\
Confirmasne sublationem...?"

320 "Hoc constitutum solum"

321 "Sequentes"

322 "Omne"

323 "Constitutum mutare"

324 "Seligere constitutum, postea Mutare."

325 "Exsegui"

326 "Constitutum mutare"

327 "Error internus accidit dum selectione\n\
constituti. Id mutatum non est."

328 "Exsegui"

329 "Conventum mutare"

330 "Selige libellum, postea Mutare."

331 "Exsegui"

332 "Constitutum mutare"

333 "Hoc constitutum partem seriei recurrentis est.\n\
Confirmasne mutationem...?"

335 "Hoc constitutum solum"

336 "Sequens"

337 "Omne"

340 "Libellus"

341 "Aditus"

342 "Inserere"

343 "Mutare"

348 "Addere licentiam"

349 "Editorium conventi"

350 "Error selectionis, continuare non potest.\n"

351 "Selectio a usore obstata.\n"

352 "Debes seligere partem programmae.\n"

353 "Sine horam"

354 "Totus dies"

355 "Aperire scapum callog non potest.\n\
Opus rescissum est. Libellus"

356 "Per jussam usoris, opus rescissum.\n\
Libellus"

357 "Valor vitiosa in zona DIE.\n\
Opus rescissum est. Libellus"

358 "Valor vitiosa in zona INITIO.\n\
Opus rescissum est. Libellus"

359 "Valor vitiosa in zona FINIS.\n\
Opus rescissum est. Libellus"

360 "Debes indicare DIEM.\n\
Opus rescissum est. Libellus"

361 "Debes indicare valor INITII.\n\
Opus rescissum est. Libellus"

362 "Debes indicare COMMENTARIA.\n\
Opus rescissum est. Libellus"

363 "Valores ITERARE et USQUE vitiosas aut incompatibles.\n\
Opus rescissum est. Libellus"

364 "Opus editorii offendit."

365 "Exsegui"

367 "Libellus jam exstat.\n\
Opus rescissum est. Libellus"

368 "Libellus deest.\n\
Opus rescissum est. Libellus"

370 "Error auctoritatis. Licentia refusée.\n\
Opus rescissum est. Libellus"

378 "Error d'allocation memoriam - Mémoria nimis parva.\n\
Opus rescissum est. Libellus"

383 "Error ignotum.\n\
Opus rescissum est. Libellus"

386 "Horam finis constituti est ante horam initii ejus.\n\
Visne conjicere illam a postridie ?"

387 "Constitutum conjicere"

389 "Postridie"

390 "Arcano:"

391 "Locus libelli usoris:"

392 "Initium et finis diei:"

393 "Initium:"

394 "Finis:"

395 "Propositum horae:"

396 "12 horae"

397 "24 horae"

398 "Conspectus in absentem aliquis:"

399 "Anno"

400 "Mens"

401 "Hebomadas"

402 "Die"

403 "Conspectus initiale libelli:"

404 "Aditus usor"

405 "Selige au moins unam licentiam."

406 "Exsegui"

407 "Parametra aditus circuli -- Tollere"

408 "Primum selige nominem."

409 "Exsegui"

410 "Nomen usoris:"

411 "Addere nominem"

412 "Permissiones"

413 "Permissiones"

414 "Tollere nominem"

415 "P = Perlustrare I = Inserere S = Tollere"

416 "Permissiones:"

417 "Perlustrare"

418 "Inserere"

419 "Tollere"

420 "Destinatio:"

421 "Machina pressoria"

422 "Scapus"

423 "Machina pressoria:"

424 "Index:"

425 "Optiones:"

426 "Scapus:"

427 "Latitudo:"

428 "Altitudo:"

429 "Situs:"

430 "Unciae ab senestra"

431 "Unciae ab ima"

432 "Unités:"

433 "Exemplares:"

434 "Includere:"

435 "Proponere horam verbaque"

436 "Proponere horam solam"

437 "Nihil Proponere"

438 "Ordinatio dierum:"

439 "MM | DD | AA"

440 "DD | MM | AA"

441 "AA | MM | DD"

442 "Separatio dierum:"

443 "Spatium"

444 "Conservare optiones libelli"

445 "Error accidit dum perscriptione in ~/.desksetdefaults. Verifica\n\
licentias facendi hoc operem habes."

446 "Exsegui"

447 "Legere optiones libelli"

448 "Error accidit dum lectione ex ~/.desksetdefaults. Verifica\n\
licentias facendi hoc operem habes."

449 "Exsegui"

450 "Constitutum Editor - Adjumentum"

451 "Mutationes factae perscriptae non sunt.\n\
Perscribere aut rescindere eam  aut redire\n\
locum superiorem in capsa dialogi potes."

452 "Conservare"

453 "Tollere"

454 "Conservare optiones libelli"

456 "Exsegui"

458 "Libelli -  Optiones"

459 "Species:"

460 "Applicare"

463 "Adjumentum"

464 "ps_open_file(): Indica indicem aut scapum.\n"

465 "ps_open_file(): Indicem %s vitiosum.\n"

466 "w+"

467 "ps_open_file(): Aperire scapum %s non potest.\n"

468 "Pagina"

469 "Conspectus diei (libellus)"

470 "Mane"

471 "Postmeridie"

472 "pm"

473 "Index pensorum (libellus)"

474 "Index constitutorum (libellus)"

475 "Pagina"

476 "super"

477 "Conspectus mensis (libellus)"

478 "super"

479 "Pagina"

480 "Sol"

481 "Lun"

482 "Mar"

483 "Mer"

484 "Jov"

485 "Ven"

486 "Sat"

487 "ps_init_printer(): Aperire scapum postscript prologi: %s non potest.\n"

488 "super"

489 "   Pagina"

490 "Conspectus hebdomadis (libellus)"

491 "L"

492 "M"

493 "Me"

494 "J"

495 "V"

496 "Sa"

497 "S"

505 "Sat"

506 "Sol"

507 "Conspectus anni (libellus)"

508 "Conspectus anni (libellus)"

523 "Index pensorum: Anno %d."

524 "Index constitutorum : Anno %d."

525 "Index pensorum: %s"

526 "Index constitutorum: %s"

527 "Index pensorum: Hebdomas %s"

528 "Index constitutorum: Hebdomas %s"

529 "Index pensorum: %s"

530 "Index constitutorum: %s"

531 "Omnis %d %s"

532 "DTCM: Iterare omne"

533 "Iterare Omne:"

534 "Frequentia:"

535 "Ut:"

536 "Arcanum:"

537 "Preameditatio constitutorum"

538 "Visne praemeditare hoc constitutum dum\n\
ultima aut 4a hebdomas mensis ?"

540 "Ultima hebdomas"

541 "4a hebdomas"

542 "Omnis %d %s"

543 "Omnis %d %s"

544 "Omnis %d %s"

559 "Aspicere %s..."

560 "Libellus - Propon. alter libellum"

561 "Nomen usoris:"

562 "Proponere"

564 "Adjumentum"

565 "Autor"

566 "Tollere pensum"

567 "Seligere pensum, postea Tollere."

568 "Exsegui"

569 "Tollere pensum"

570 "Error internus accidit dum selectione\n\
selectione pensi. Celle-ci n'a pas été supprimée."

571 "Exsegui"

572 "Tollere pensum"

573 "Hoc pensum partem seriei recurentis est.\n\
Confirmasne detractionem...?"

575 "Hoc pensum solum"

576 "Sequentes"

577 "Totas"

578 "Mutare pensum"

579 "Hoc pensum partem seriei recurentis est.\n\
Confirmasne mutationem...?"

581 "Hoc pensum solum"

582 "Sequentes"

583 "Totas"

584 "Mutare pensum"

585 "Seligere pensum, postea Mutare."

586 "Exsegui"

587 "Mutare pensum"

588 "Error internus accidit dum\n\
selectione pensi. Id mutatum non est."

589 "Exsegui"

590 "Dies solvendi:"

591 "Editorium pensi"

595 "Hebdomadas incipiens %s"

596 "Die Lunae %d"

597 "Die Marti %d"

598 "Die Mercurii %d"

599 "Die Jovis %d"

600 "Die Veneris %d"

601 "Die Saturni %d"

602 "Die Solis %d"

603 "Induce nominem in zona Nomen usoris."

604 "jam in indice adest."

605 "Adjumentum"

606 "Error - Libellus"

607 "Error internus accidit lors de l'enregistrement nominem libelli."

608 "Exsegui"

609 "Libellus - Error"

610 "Error internus accidit dum extractione nominis libelli."

611 "Exsegui"

612 "Prooemium..."

613 "De libello..."

617 "Hodie"

618 "Debes indicare parametrum post verbum -session.\n"

619 "Induce nominem libelli secundum formam: <usor>@<nomen_hospitis>"

620 "Libellus ignotus. Nominem dare oportet: <nomen>%s"

621 "Induce nominem libelli secundum formam: <usor>@<nomen_hospitis>"

622 "Libellus ignotus. Nominem hospitis dare oportet: %s@<nomen_hospitis>"

623 "Libellus dies ante 1us januarii 1970 non proponet."

624 "Libellus dies post 31 decembris 2037 non proponet."

625 "Minus"

626 "Plus"

627 "Fac labi constitutum"

628 "Hora Commentaria"

629 "Plus"

631 "%d casum(s) inventus(i)"

632 "Seligere constitutum proponendum in indico."

633 "Libellus selectus"

634 "Libelli selecti"

635 "Minor"

636 "Major"

637 "Major"

641 "Minister invenire inscriptionem retis\n\
loci indicati non potuit: nomen hospitis vitiosus."

642 "Daemon rpc.cmsd non refertur. Verifica \n\
id  emendate instruetus in ordinatro est."

643 "Invenire libellum non potest. Libellus"

644 "Horae constituti:"

645 "Tempus:"

646 "Minutas"

647 "Investigatio %s..."

648 "SunDex"

649 "Libellus - Circulus temporalis"

650 "Hora loci"

652 "Hora GMT"

653 "GMT"

654 "Horae"

655 "Ita"

656 "Applicare"

658 "Adjumentum"

659 "Circulus temporalis:"

660 "Circulus temporalis:"

662 "Circulus temporalis:"

663 "Minor"

664 "Major"

666 "Major"

667 "Libellus diem ante 1us januarii 1970 non proponet."

668 "Libellus diem post 31 decembris 2037 non proponet."

670 "Dtcm"

671 "Versio"

672 "Révision"

674 "Copyright (c) 1993, 1994:"

675 "Hewlett-Packard Company"

676 "International Business Machines Corp."

677 "Novell, Inc."

678 "Sun Microsystems, Inc."

679 "Serie..."

680 "Claudere"

681 "Programmatores"

682 "Haec programma creatus est a:"

683 "Claudere"

684 "Inducere spatium vel litteram tabulationis in nominibus usorum non licet."

685 "Nomen usoris:"

686 "Addere nominem"

687 "Tollere nominem"

688 "Optiones indicis Perlustrare"

689 "Profecto"

690 "Applicare"

691 "Restituere"

693 "Adjumentum"

696 "Syntaxis:\n\
\tdtcm_admin [ -d ] [ -a actio ] [ -c libellus][ -s <mm/jj/aa> ] [ -e <mm/jj/aa> ] [-f nomen_scapi]\n"

697 "Indicavisti operem programma facere non potest (\"%s\").\n"

698 "\n\
Aperire scapum scribendi non potest \"%s\".\n"

699 "\n\
Aperire scapum legendi non potest \"%s\".\n"

700 "Tollere"

702 "Adjumentum"

703 "contextus"

704 "Anno %d"

705 "%s"

706 "Hebdomadas %s"

707 "%s"

708 "Modus iterationis hujus constituti ignotus est; Omne \n\
casus mutabuntur. Confirmasne detractionem ?"

710 "Exsegui"

711 "Modus iterationis hujus constituti ignotus est; Omne \n\
casus tollentur. Confirmasne detractionem ?"

712 "Exsegui"

713 "Oportet seligere diem initii ante diem finis."

714 "Index nihil constitutum continet; proponere non potest."

715 "Libellus - Quaerere per diem"

716 "Modus iterationis hujus constituti ignotus est; Omne \n\
casus mutabuntur. Confirmasne detractionem ?"

717 "Exsegui"

718 "Modus iterationis hujus constituti ignotus est; Omne\n\
casus mutabuntur. Confirmasne  mutationem ?"

720 "Exsegui"

721 "Hora et textus aperti ceterorum"

722 "Hora aperta ceterorum"

723 "Nulla data aperta ceterorum"

724 "Oportet indicare commentarias ut constituti\n\
sine horas. Opus rescissum est. Libellus"

725 "Rem libelli deest.\n\
Opus rescissum est. Libellus"

727 "Dépassement de délai de la requête. Vérifiez que\n\
rpc.cmsd est installé correctement sur le système."

728 "Libellus - Exscribere"

729 "Instrumentum pressorium:"

730 "Exemplares:"

731 "Ab:"

732 "Usque:"

733 "Optiones pressoriae:"

734 "Copiare in scapo:"

735 "Exscribere"

736 "Libellus : Error - Exscribere"

737 "Adjumentum"

738 "Index aditus:"

739 "Licentias aditus:"

740 "Addere"

741 "Tollere"

742 "Mutare"

743 "Publicus:"

744 "Semi-privatus:"

745 "Privatus:"

746 "Aspicere"

747 "Inserere"

748 "Mutare"

749 "Ad addendum rem in indice aditus, debes definire nominem licentias aditusque ejus."

750 "Parametri aditus circuli -- Addere"

751 "Cette entrée jam adest dans la liste d'accès. Voulez-vous la modifier ?"

752 "Parametri aditus circuli -- Addere"

753 "Mutare"

755 "Parametri aditus circuli -- Mutare"

756 "Pour modifier un élément de la liste d'accès, vous devez indiquer son nom et ses droits d'accès."

757 "Parametri aditus circuli -- Mutare"

758 "minuit"

759 "valor"

760 "valor"

761 "Tollere"

762 "Parametri editorii absentem aliquis"

763 "Parametri proponere"

764 "Indices et Licentias"

765 "Parametra machinae pressoriae"

766 "Forma dierum"

767 "Ita"

768 "Restituere"

772 "Perscribere locum libelli vacuum\n\
aut quod spatii contineret non licet.\n\
Insignes perscripti non sunt."

773 "Perscribere conspectum libelli initii \n\
vacuum aut quod spatios contineret non licet.\n\
Insignes perscripti non sunt."

774 "ps_open_file(): Ad compiandum, debes indicare nominem scapi.\n"

775 "Debes indicare repetitionem sequentem.\n\
Opus rescissum est. Libellus"

776 "Repetitio debet continere nullum spatium.\n\
Opus rescissum est. Libellus"

777 "Les valeurs d'avance doivent être numériques et,\n\
éventuellement, signées. Opus rescissum est. Libellus"

778 "Index pensorum - Adjumentum"

779 "Mutationes perscriptae non sunt.\n\
Perscribere aut rescindere eas aut redire\n\
locum superiorem in capsa dialogi potes."

780 "Tollere"

781 "Aspicere"

782 "Totum"

783 "En attente"

784 "Terminatus"

785 "Profecto"

786 "Applicare"

788 "Adjumentum"

789 "Genus pensi:"

790 "contextus"

791 "Modus iterationis hujus pensi ignotus est; omne \n\
casus mutabuntur. Confirmasne mutationem ?"

793 "Exsegui"

794 "Modus iterationis hujus constituti ignotus est; omne\n\
casus mutabuntur. Confirmasne mutationem ?"

796 "Exsegui"

797 "Munus"

798 "Dies solvendi:"

799 "Terminatus"

800 "Inserere"

801 "Mutare"

802 "Tollere"

803 "Expungere"

805 "Adjumentum"

806 "Anno %d"

807 "%s"

808 "Hebdomadas %s"

809 "%s"

810 "Induce diem initii postea 1/1/1970."

811 "Dies initii vitiosum."

812 "Induce diem finis ante 1/1/2038."

813 "Dies finis vitiosum."

814 "Debes indicare annum post 1969 et ante 2038."

815 "Debes indicare annum post 1969 et ante 2038."

816 "Dies"

817 "Hebdomades"

818 "Mensis"

819 "Valor temporis integer numeris sine signum esse oportet.\n\
Insignes perscriptae non sunt."

820 "Valor initii horam validam esse oportet.\n\
Insignes perscriptae non sunt."

$ 821 "Indicavisti latitudinem  ut opere pressoria vitiosam.\n\
$ Insignes perscriptae non sunt."
$ "print width" has been replaced by "right margin".
821	"Indicavisti valorem marginis dextrae  ut opere pressoria vitiosam.\n Insignes perscriptae non sunt."

$  "Indicavisti altitudinem vitiosam ut opere pressoria.\n\
$ Insignes perscriptae non sunt"
$ "print height" has been replaced by "bottom margin".
822	"Indicavisti valorem marginis deorsum  ut opere pressoria vitiosam.\n Insignes perscriptae non sunt"

825 "Dies"

826 "Hebdomadas"

827 "Mensis"

828 "Dies:"

829 "Initio:"

830 "AM"

831 "PM"

832 "Finis:"

833 "AM"

834 "PM"

835 "Commentaria:"

836 "Frequentia"

837 "Inserere/Mutare pensum"

839 "Libellus: Repetitio"

840 "Claudere"

841 "Selige \"Addere nominem\" ad addendum nominem aut \"Applicare\" ad confirmandum mutationes."

842 "Percontationes trasmittae \n\
nullum constitutum continent."

843 "Opus labi-ponere offendit."

844 "Percontationes trasmittas invenire non potest."

845 "Opus labi-ponere offendit.\n\
Error internus de cohérence."

846 "Conservare"

847 "Restituere"

848 "Dies"

849 "Hora"

850 "Commentaria"

851 "Aspicere constitutum"

852 "Semel"

853 "Quotidie"

854 "Hebomadalis"

855 "Omni bini hebdomades"

856 "Omni mensis, per numero diei"

857 "Omni mensis, per nomine diei"

858 "Quotannis"

859 "Ab die lunae usque die venerii"

860 "Lun, Mer, Ven"

861 "Mar, Jov"

862 "Iterare Omne..."

863 "2"

864 "3"

865 "4"

866 "5"

867 "6"

868 "7"

869 "8"

870 "9"

871 "10"

872 "11"

873 "12"

874 "13"

875 "14"

876 "semper"

877 "Min."

878 "Hor."

879 "Dies"

880 "Adjumentum"

881 "Error internus #1: Identificateur d'agenda/entrée vitiosus.\n\
Opus rescissum est. Libellus"

882 "Error internus #2: Identificateur de session vitiosus.\n\
Opus rescissum est. Libellus"

883 "Error internus #3: Data vitiosae.\n\
Opus rescissum est. Libellus"

884 "Error internus #4: Valor indiquée pour un attribut\n\
en lecture seule. Opus rescissum est. Libellus"

885 "Error internus #5: Genus datorum vitiosus indicatus pour1\n\
une valeur d'attribut. Opus rescissum est. Libellus"

886 "Error internus #6: L'attribut indiqué n'est pas pris en charge\n\
par cette version de l'agenda. Opus rescissum est. Libellus"

887 "Error internus #7: La fonction indiquée n'est pas prise en charge\n\
par cette version de l'agenda. Opus rescissum est. Libellus"

888 "Error internus #8: Operator indicatus vitiosus est.\n\
Opus rescissum est. Libellus"

890 "Error - Functiones libelli"

891 "Exscribere"

892 "Dies indicatae ad exscribendum post anno 1969 et ante 2038 esse oportet."

893 "Exscribere"

894 "Dies \"Ab\" vitiosum"

895 "Exscribere"

896 "Dies \"Usque\" vitiosum"

897 "Exscribere"

898 "Dies \"Ad\" indicata ad exscribendum post diem \"Ab\" esse oportet."

899 "Initio indicis pensorum: %s"

900 "Initio indicis constitutorum: %s"

901 "Iterare omne..."

902 "Ab die lunae usque die venerii"

903 "Lun, Mer, Ven"

904 "Mar, Jov"

905 "Iterare omne..."

906 "Fac labi pensum"

907 "Spatium nimis parvum pro scapo libelli.\n\
Opus rescissum est. Libellus"

908 "Definire valorem repetitionis nullam non licet.\n\
Insignes perscriptae non sunt"

909 "Definire valorem repetitionis quod spatium continet \n\
non licet. Insignes perscriptae non sunt"

910 "Valorem repetitionis numeri esse oportet, éventuellement\n\
signés. Insignes perscriptae non sunt"

$ 911 "Vous avez indiqué une position incorrecte pour le décalage à gauche.\n\
$ Insignes perscriptae non sunt"
$ "position from left offset" has been changed to "left margin".
911	"Valorem vitiosam marginis sinistrosum indicavisti.\n Insignes perscriptae non sunt"

$ 912 "Vous avez indiqué une position incorrecte pour le décalage à droite.\n\
$ Insignes perscriptae non sunt"
$ "position from right offset" has been changed to "top margin".
912	"Valorem vitiosam marginis sursum indicavisti.\n Insignes perscriptae non sunt"

913 "Prima linea commentariorum pensi textum continere  oportet."

914 "Opus editorii libelli offendit."

915 "Opus editorii libelli offendit."

916 "Tempus doit être inférieure à 24 horas.\n\
Insignes perscriptae non sunt."

917 "Delineatio\n\
deest"

918 "Delineatio\n\
deest"

919 "Libellus"

920 "propositus."

921 "Nequeo invenire libellum:"

922 "De libello"

923 "Tollere"

924 "Tollere"

925 "Tollere"

926 "Claudere"

927 "Tollere"

928 "Tollere"

929 "Tollere"

930 "Inserere"

931 "Mutare"

932 "Tollere"

933 "Expungere"

934 "Tollere"

935 "Adjumentum"

936 "Tollere"

937 "Tollere"

938 "Tollere"

939 "Tollere"

940 "Claudere"

941 "Claudere"

942 "Tollere"

943 "Tollere"

944 "Tollere"

945 "Tollere"

946 "Tollere"

947 "Tollere"

948 "Claudere"

949 "Tollere"

950 "Tollere"

951 "Tollere"

952 "Claudere"

953 "Tollere"

954 "Claudere"

955 "Tollere"

956 "Tollere"

957 "Tollere"

958 "Tollere"

959 "Tollere"

960 "Tollere"

961 "Tollere"

962 "Tollere"

963 "Libellus - Editorium indicis"

964 "De parte"

965 "Index  pensorum..."

966 "Pensum..."

967 "Versio ministri libelli"

968 "Versio datorum libelli"

969 "Iteratio (frequentia)"

970 "Valor iterationis debet esse integer sine signum."

971 "Hora Libelli"

972 "Commentaria"

973 "Quaerere omne"
974 "Quaerere ab"
975 "ad"
976 "Genus de rapport :"
977 "Conspectus diei"
978 "Conspectus hebdomadis"
979 "Conspectus mensis"
980 "Conspectus anni"
981 "Index constitutorum"
982 "Index pensorum"
983 "Nomen usoris"
984 " Hoc constitutum partem seriei recurrentis est.\n Confirmasne l'insertion...?"
985 "Repetitiones"
986 "Tinnitus"
987 "Palpebrare"
988 "Nuntius subitus"
989 "Epistula"
990 "Mittere ad :"
992 "%A, %e %B, %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar day view.  In the C locale
$ 	   it has the form:
$ 
$ 		Monday, January 16, 1995
$ 
$ 	   strftime conversion string: "%A, %B %e, %Y" is used.  
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
993 "Hebdomadas incipiens %A %e %B %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar week view.  In the C locale
$ 	   it has the form: 
$ 
$ 			Monday, January 16, 1995
$ 
$ 	   strftime conversion string: "%A, %B %e, %Y" is used.  The string
$ 	   will be used in a label that looks like this:
$ 
$ 			Week Starting Monday, January 16, 1995
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
994 "dies"
995 "hebdomas"
996 "duae hebdomades"
997 "mensis"
998 "anni"
1002 "Contribue quoque :"
1003 "Hoc constitutum in libellum alterum adest.\nConfirmare mutationem ?"
1004 "Hoc constitutum in libellum alterum adest.\n Confirmare detractionem ?"
1005 "Tollere ex"
1006 "Mutare in"
1007 " Error internus accidit dum selectione\n\
du constitutum. Hoc mutatus non est."
1008 "Libellus constitutum : Adjumentum"
1009 " Error internus accidit dum selectione\n\
pensi. Hoc mutatus non est."
1010 "Libellus : libellos comparare"
1011 "Valor vitiosa in zona \"Dies solvendi\".\nOpus sublata. Libellus"

1012 "Libellus -  Index pensorum"

1042 "Inserere aditus negatus est: "
1043 "Tollere aditus negatus est: "
1044 "Aspicere aditus negatus est: "
1045 "Tollere ut"
1046 "Constitutum sublatum\n"
1047 "Hoc constitutum: '%s' finem habet\n"
$ 	/* NL_COMMENT
$ 	   
$ 	   The following four messages (1047-1050) will be printed to stdout 
$ 	   and can have the following two forms:
$ 
$ 		"This appointment: '<appt text>' has an end
$ 		 time earlier than its begin time.  Do you
$ 		 want to schedule it into the next day? [Y/N]  "
$ 
$ 	   or 
$ 
$ 		"This appointment has an end
$ 		 time earlier than its begin time.  Do you
$ 		 want to schedule it into the next day? [Y/N]  "
$ 
$ 	   The text <appt text> and [Y/N] should not be translated.
$ 
$ 	*/
1048 " Hora finis constituti \n"
1049 " ante horam initii ejus est.\n"
1050 " Visne conjicere finem postridie ? [Y/N]  "
1051 " Constitutum '%s' est pars serei recurrentis.  "
$ 		/* NL_COMMENT
$ 
$ 		   Message numbers 1051-1057 are printed to stdout and
$ 		   should appear like:
$ 
$ 		   "The appointment '<appt text>' is part of a repeating series. Do you want to:
$ 			1.  Delete all of them
$ 			2.  Delete this on only
$ 			3.  Delete forward
$ 			4.  Cancel
$ 			Option [1-4]: "
$ 
$ 		*/
1052 "Visne :"
1053 "\n\t1. tollere omnes"
1054 "\n\t2.  tollere hoc solum"
1055 "\n\t3.  tollere hoc sequentesque"
1056 "\n\t4.  Relinquere"
1057 "\n\tOptio [1-4]: "
1058 "Dies vitiosus.\n"
1059 "Hora initii vitiosa.\n"
1060 "Hora finis vitiosa.\n"
1061 "Zona Dies vacua est aut deest.\n"
1062 "Zona Initio vacua est aut deest.\n"
1063 "Zona Commentariorum vacua est aut deest.\n"
1064 "Zonae Iterare et Ut alienae sunt.\n"
1065 "Inserere constitutum rescindit\n"
1066 "Constitutum insertum non est."
1067 "Dies indicatum vitiosum :"
1068 "Constitutum ut"
1069 "Neque constitutum ut"
1070 "Libellus : Error - libellos comparare"
1072 " Libellus : Error - Perlustrare"
1073 " Libellus : Error - labi et ponere"
1074 "Constitutum libelli"
1075 " Libellus : Error - Mutare constitutum"
1076 " Libellus : Adjumentum"
1078 " Libellus : Index aditus et licentias - Addere"
1079 " Libellus : Error - Parametri editorii"
1083 " Libellus : Error - Afficher parametri"
1085 " Libellus : Error - Parametri instrumenti pressorii"

1086 "Libellus - Index constitutorum"

1087 "Ab %1$2d:%2$02d%3$s usque %4$2d:%5$02d%6$s"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1087 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  In the C locale it would
$ 				   look something like this:
$ 
$ 				   ``From 11:00am to 1:00pm''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> am or pm
$ 					$4	-> stop hour
$ 					$5	-> stop minute
$ 					$6	-> am or pm
$ 
$ 				*/
1088 "%1$2d:%2$02d%3$s"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1088 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  It is used when an appt
$ 				   does not have and ``end'' time.  In the 
$ 				   C locale it would look something like this:
$ 
$ 				   ``11:00am''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> am or pm
$ 
$ 				*/
1089 "Ab %1$02d%2$02d usque %3$02d%4$02d"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1089 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  This string is used when
$ 				   a user has asked that times be displayed
$ 				   in 24 hour format.  In the C locale it 
$ 				   would look something like this:
$ 
$ 				   ``From 0100 to 1600''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> stop hour
$ 					$4	-> stop minute
$ 
$ 				*/
1090 "%1$02d%2$02d"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1090 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  This string is used when
$ 				   an appt does not have an end time and the
$ 				   user has asked that times be displayed
$ 				   in 24 hour format.  In the C locale it 
$ 				   would look something like this:
$ 
$ 				   ``1600''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 
$ 				*/
1091 "%B %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar month view.  In the C locale
$ 	   it has the form:
$ 
$ 		July, 1995
$ 
$ 	   strftime conversion string: "%B, %Y" is used.
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
1092 "%Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar year view.  In the C locale
$ 	   it has the form:
$ 
$ 		1995
$ 
$ 	   strftime conversion string: "%Y" is used.
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
$ 	/* NL_COMMENT
$ 	The following message were added because message numbers from
$    	IBM and Sunsoft conflicted - they both used the same message number
$    	for different messages.  The IBM message number was changed as
$    	follows:
$ 
$		1100 was 978 from IBM
$		1101 was 979 from IBM. 
$		1102 was 981 from IBM. 
$		1103 was 982 from IBM. 
$		1104 was 985 from IBM. 
$		1105 was 986 from IBM. 
$ 	*/

1100 "\n\n\
\t** Pensum (libelli) **\n\n\
\tDies solvendi:\t%s\n\
\tHora:\t%s\n\
\tCommentaria:\t\t%s"

1101 "Inserere constitutum"

1102 "Inserere pensum"

1103 "Hoc pensum pars seriei recurentis est.\n\
Visne inserere id...?"

1104 "Valor vitiosum in zona Horae.\n\
Opus rescissum est. Libellus."

1105 "Debes indicare horam.\n\
Opus rescissum est. Libellus."

$ Message numbers 1106-1110 represent choices for the content of
$ left and right headers and footers on the printed page.  These
$ items are displayed in option menus in the "Printer Settings..."
$ category of the "Options..." dialog.
1106	"Dies"
1107	"ID usoris"
1108	"Numero paginae"
1109	"Genus relationis"
1110	"Nihil"
$ Message 1111 is placed in the title bar of an error dialog if an
$ error is encountered when the user invokes "Setup..." from the
$ "Print..." dialog box.  Message 1112 is the text displayed in
$ that error dialog.
1111	"Libellus Error - Facies pressoriae"
1112	"Error ministri pressorium (PDM) - facies corruit."
$ Message 1113 is the error message displayed if the user selects
$ "Print" from the "Print..." dialog box while an invalid printer
$ name is specified.
1113	"Instrumentum pressorium vel minister pressorium vitiosus."
$ Message 1114 is placed in the title bar of an error dialog if an
$ error is encountered when the user invokes "Print" from the
$ "Print..." dialog box with the "Print to File" toggle selected.
$ Message 1115 is the text displayed in that error dialog.
1114	"Libellus : Error - Exscribere in scapo"
1115	"Error - exscribere in scapo non potest."
$ Message 1116 is placed in the title bar of an information dialog
$ if the operation completes successfully when the user invokes "Print"
$ from the "Print..." dialog box with the "Print to File" toggle
$ selected.  Message 1117 is the text displayed in that information dialog.
1116	"Libellus : Exscribere in scapo"
1117	"Exscribere in scapo terminatus."
$ Message 1118 is placed in the title bar of a warning dialog if a
$ font cannot be found during the "Print" operation.  Message 1119
$ is the text displayed in that warning dialog; the %s will be replaced
$ by the name of the font.
1118	"Libellus : Monitio - Exscribere"
1119	"Monitio - Onerare typum %s non potest."
$ 
$ Message 1120 appears in an error dialog when an appointment cannot
$   be scheduled. (the original was vague, so the Latin is dubious) 
1120	"Constitutum accidere in diem indicatus non potest.\nOpus rescissum est."

$ 
$ Message 1121 is placed in the title bar of a warning dialog if a
$ print job fails because the Print Server returns BadAlloc.  Message
$ 1122 is the text displayed in that warning dialog.
1121	"Libellus : Error ministri pressorium"
1122	"Opus pressoriae offendit.\n\nMinister pressoriae X temporarie satis opes non habet."

$set 2
$ *****************************************************************************
$ **
$ ** Message set for  DieFromToolTalkError Dialog
$ **
$ *****************************************************************************
$ These are the messages for the ToolTalk error dialog
$ "-NEW"
1 Libellus - Monitio
$ "-NEW"
2 "connectere cum ToolTalk non potest:\n%s\n"
$ "-NEW"
3 Profecto
$ "-NEW"
4 "Libellus : Constituti Editor - Monitio"
