$ $XConsortium: dtcopy.msg /main/5 1996/11/19 18:29:23 rws $
$ *****************************************************************************  
$ **  
$ **  File:        dtcopy.msg  
$ **  
$ **  Project:     CDE File Manager  
$ **  
$ *****************************************************************************  
$quote "

$set 2
$ ****** Module: main_dtcopy.c ******  

3 "scapus"

4 "scapus"

5 "sub-index"

6 "sub-index"

7 "Error(es): nulla"

8 "Error(es): %d"

10 "Syntaxi: %s [optiones ...] fons destinatio\n"

11 "Rector scaporum - Movere indicem"

12 "Rector scaporum - Copiare indicem"

13 "%s sublatus(i) non fuit propter errores."

14 "Opus terminatum."

15 "Rescindetus(i) in"
$ ** Message 20 - 32  
$ ** LongFileOpNames ... message number = op + 20.  

20 "tractatio ad"

21 "aperire"

22 "aperire"

23 "aperire"

24 "vincire "

25 "delere "

26 "copiare "

27 "creare indicem"

28 "copiare vinculum"

29 "creare vinculum"

30 "in effectu"

31 "copia est"

32 "vinculum est"

33 "vocare"

$set 3        Redefine set#

$ ****** Module: copydialog.c ******  

1 "Reprendre"

2 "Obstare"

3 "Movere:"

4 "Copiare:"

5 "In indice:"

7 "Cette action va annuler l'opération de copie. Tous les\n\
fichiers copiés resteront dans le dossier de destination."

10 "Cette action va annuler le déplacement. Tous les fichiers\n\
déplacés resteront dans le dossier de destination."

11 "Copiare indicem - Monitio"

12 "Movere indicem - Monitio"

13 "Rescindere copiam"

14 "Continuare copiam"

15 "Rescindere motionem"

16 "Continuare motionem"

17 "Movetus"

18 "Copiatus"

19 Nequeo movere indicem in ipsum \n\
%s\n\n

20 Nequeo copiare indicem in ipsum\n\
%s\n\n


$set 4        Redefine set#

$ ****** Module: errordialog.c ******  

1 "Error(es) %s\n\
%s"

2 "Intermissio si error adv."

3 "Copiare indicem - Error"

4 "Movere indicem - Error"

5 "Movere indicem - Error"

6 "Copiare rem - Error"

7 "Delere rem (canistrum) - Error"

8 "Injicere rem\n\n\
    %s\n\n\
in canistrum non licet.\n\n\
Pour vous accorder l'autorisation d'accéder en lecture \n\
à l'objet, utilisez l'option Modifier les droits d'accès\n\
du menu instantané de l'objet ou du menu Sélectionné(s).\n\n\n\
Remarque: Si l'objet est un dossier, vous devez \n\
également avoir accès en lecture à tous les objets\n\
qu'il contient pour pouvoir le mettre dans la corbeille."

9 Aperire %s non potest


$set 5        Redefine set#

$ ****** Module: overwrtdialog.c ******  

1 "Scapus vocatus\n\
%s\n\
jam adest in indice\n\
%s"

2 "Movere indicem - Delere scapum"

3 "Substituere scapum exstans"

4 "Vocare scapum exstans :"

5 "Vocare rem novam:"

6 "Contemnere hoc scapum"

7 "Applicare hanc  actionem aux conflits nominum"

8 "Actio:"

9 "Copia indicis - Substituere scapum"

10 "%s\n\
jam adest: selige nominem alterum."

11 "Substitutio scapi - Error"

12 "%s\n\
vocari nomine\n\
%s\n\
%s non potest"

$set 6        Redefine set#

$ ****** Module: utils.c ******  
$ ** Button labels.  

1 "Ita"

2 "Obstare"

3 "Relinquere"

4 "Adjumentum"

5 "Copia indicis - Adjumentum"

6 "Continuare"

7 "Rescindere copiam"

8 "Rescindere motionem"
