$ $TOG: dticon.msg /main/7 1999/09/17 12:18:48 mgreess $
$ *************************************<+>*************************************  
$ *****************************************************************************  
$ **  
$ **  File:        dticon.msg  
$ **  
$ **  Project:     HP DT Icon Editor  
$ **  
$ **  Description:  
$ **  -----------  
$ **  This file is the source for the message catalog for dticon  
$ **  
$ **  
$ *****************************************************************************  
$ **  
$ **     (c) Copyright 1992, 1993, 1994 Hewlett-Packard Company  
$ **     (c) Copyright 1993, 1994 International Business Machines Corp.  
$ **     (c) Copyright 1993, 1994 Sun Microsystems, Inc.  
$ **     (c) Copyright 1993, 1994 Unix System Labs, Inc., a subsidiary of  
$ **         Novell, Inc.  
$ **  
$ **     All Rights reserved  
$ **  
$ **  
$ *****************************************************************************  
$ **  
$quote "

$set 2
$ *****************************************************************************  
$ ** _DtMessage set for fileIODialog.c  
$ **  
$ ** messages 10-16 are for the FileSelectionBox widget (default labels)  
$ *****************************************************************************  

2 "Pictor iconis - I-E scapi"

4 "Pictor iconis - I-E scapi"

6 "Pictor iconis - Perscribere in"

8 "Pictor iconis - Aperire scapum"

10 "Redintegrare"

12 "Indices"

14 "Scapi"

16 "Induce nominem scapi:"

17 "Induce nominem scapi:"

18 "Redintegrare"

20 "NIHIL TITULUS"

22 "Aperire"

24 "Perscribere"

$set 4        Redefine set#

$ *****************************************************************************  
$ ** _DtMessage set for newIconDialog.c  
$ **  
$ *****************************************************************************  

2 "newIconDialog"

4 "Pictor iconis - Dimensiones aptare"

6 "Profecto"

8 "Relinquere"

10 "Adjumentum"
$ accusatif pour une mesure. Latitudo, inis f. = largeur
12 "Novam latitudinem:"

14 "Novam altitudinem:"

$set 6        Redefine set#

$ *****************************************************************************  
$ ** _DtMessage set for queryDialog.c  
$ **  
$ *****************************************************************************  

2 "Pictor iconis - Monitio"

6 "Profecto"
$ ** DO NOT LOCALIZE - the user should never see this message  

8 "Do ya really wanna?"

10 "Relinquere"

$set 8        Redefine set#

$ *****************************************************************************  
$ ** _DtMessage set for stdErrDialog.c  
$ **  
$ *****************************************************************************  

2 "Pictor iconis - Error"

4 "Continuare"

$ 
$ "-NEW"
6 Profecto

$ 
$ "-NEW"
8 "Conectere cum ToolTalk non potest:\n%s\nExeo ..."

$set 10        Redefine set#

$ *****************************************************************************  
$ ** _DtMessage set for utils.c  
$ **  
$ *****************************************************************************  
$ ** DO NOT LOCALIZE messages 2-48, they appear in the errorlog only  

2 "Cannot initialize button icon for circle"

4 "Cannot initialize button icon for solid circle"

6 "Cannot initialize button icon for polyline"

8 "Cannot initialize button icon for polygon"

10 "Cannot initialize button icon for solid polygon"

12 "Cannot initialize button icon for ellipse"

14 "Cannot initialize button icon for solid ellipse"

16 "Cannot initialize button icon for eraser"

18 "Cannot initialize button icon for line"

20 "Cannot initialize button icon for flood"

22 "Cannot initialize button icon for point"

24 "Cannot initialize button icon for rectangle"

26 "Cannot initialize button icon for solid rectangle"

28 "Cannot initialize button icon for select"

30 "Unable to parse static color no."

32 "Unable to allocate static color no."

38 "No memory(0)"

40 "No memory(1)"

42 "No memory(2)"

44 "No memory(3)"

46 "No memory(4)"

48 "No memory(5)"

50 "Impossible d'initialiser l'application de stockage des icônes."

52 "Usus parametri -f vitiosus."

54 "Usus parametri -i vitiosus."

56 "Usus parametri -session vitiosus."

58 "Dimensiones vitiosae."

60 "Scrutari imaginis offendit."

62 "Offensio operationis.\n\
Tabula colorum saturata est."

64 "Parametrum dimensionis vitiosum."

66 "(NULLUS NOMEN)"

$set 12        Redefine set#

$ *****************************************************************************  
$ ** _DtMessage set for dtIconShell.c  
$ **  
$ *****************************************************************************  

1 "Pictor iconis"

2 "2 colores"

3 "Pictor iconis -  (NULLUS NOMEN)"

4 "Optato advenis in pictorem iconis."

6 "Pingere"

8 "Colores stativi"

10 "Colores motiles"

12 "Gradus cinereorum"

14 "Pars prior"

16 "Pars posterior"

18 "Umbra sursum"

20 "Umbra deorsum"

22 "Selectio"

24 "Translucens"
$ ** message 26-198 are menu items with corresponding mnemonics  
$ ** (for set grouping information, see the comment at the end-of-file)  

26 "N"

28 "Novus..."

30 "O"

32 "Aperire..."

34 "S"

36 "Perscribere"

38 "a"

40 "Perscribere in..."

42 "Q"

44 "Exire"

46 "F"

48 "Scapum"

50 "A"

52 "Relinquere"

54 "C"

56 "Secare zonam"

58 "o"

60 "Copiare zonam"

62 "l"

64 "Glutinare zonam"

68 "G"

70 "Sinistra"

72 "D"

74 "Dextra"

76 "P"

78 "Versari zonam"

82 "V"

84 "Verticalis"

86 "H"

88 "Horizontalis"

90 "I"
$ Inverser signifie reflechir dans un miroir = reflectere
92 "Reflectere zonam"

94 "j"

96 "Aptare zonam"

98 "e"

100 "Aptare dimensionem iconis..."

102 "u"

104 "Addere signum"

106 "S"

108 "Delere signum"

110 "S"

112 "Scrutari imaginem scrinii"

114 "E"

116 "Expungere iconem"

118 "E"

120 "Mutare"

122 "G"

124 "Reticulum propositum"

128 "B"

130 "XBM"

134 "P"

136 "XPM"

138 "F"

140 "Forma eductionis"

144 "2x"

146 "3x"

148 "4x"

150 "5x"

152 "6x"

154 "8x"

156 "10x"

158 "12x"

160 "A"

162 "Ampliare"

164 "O"

166 "Optiones"

168 "G"

170 "Prooemium..."

172 "T"

174 "Muneres..."

176 "R"

178 "Relatio..."

180 "u"

182 "De parte"

188 "i"

190 "Adjumentum  adjumenti..."

192 "A"

194 "De pictore iconis..."

196 "A"

198 "Adjumentum"
$ ** message 200-are used in the "instruction" line for current drawing mode  

200 "Genus operationis vertens:"

202 "(Coloratus)"

204 "Graphis"

206 "Colorare"

208 "Linea"

210 "Lineae junctae"

212 "Recto angulo"

214 "Polygonum"

216 "Circulus"
$ Ellipse  
218 "Ellipis"

220 "Expungere"

222 "Seligere"

224 "Non licet"

$set 14        Redefine set#

$ *****************************************************************************  
$ ** _DtMessage set for help.c  
$ **  
$ *****************************************************************************  

2 "Pictor iconis - Adjumentum"

4 "Debes seligere partem\n\
in pictorem iconis."

$set 16        Redefine set#

$ *****************************************************************************  
$ ** _DtMessage set for process.c  
$ **  
$ *****************************************************************************  

2 "Scapus patens non est vel\n\
continet datas vitiosas."

4 "Perscribere datas in scapo non potest."
$ fonction pas encore disponible 
6 "Haec functio etiam non adest."

8 "Imaginem superior\n\
deest."

10 "Latitudo vel altitudo\n\
indicata(e) vitiosa(e)."

12 "Nullam zonam selectam."

14 "Nullam zonam jam\n\
secatam vel copiatam."

16 "Iconem vertens perscripta non est.\n\n\
 modificationes tuam amittebuntur."

20 "Verifica jures scapi."

22 "Restituere sessionem ex scapum non potest."

24 "Sessionem perscribere in scapo non potuit."

25 "Hic scapus jam exstat.\n\n\
Visne in locum ejus supponere ?"

$set 18
$ *****************************************************************************
$ ** _DtMessage set for event.c
$ **
$ *****************************************************************************
$quote

2 Dimensiones imaginis scrutatae = %dx%d

$ ****************************************************************************  
$ ** End of _DtMessage Catalog File  
$ ** (Comments only below this line)  
$ ****************************************************************************  
$ **  
$ ****************************************************************************  
$ ** Unique mnemonic groupings from set 12  
$ *****************************************************************************  
$ **  
$ ** Unique Set 1:  (Main Menu Bar)  
$ **  
$ **   46 F  
$ **   48 File  
$ **  
$ **   118 E  
$ **   120 Edit  
$ **  
$ **   164 O  
$ **   166 Options  
$ **  
$ **   196 H  
$ **   198 Help  
$ **  
$ **  
$ ** Unique Set 2:  (File Menu)  
$ **  
$ **   26 N  
$ **   28 New...  
$ **   30 O  
$ **   32 Open...  
$ **   34 S  
$ **   36 Save  
$ **   38 A  
$ **   40 Save As...  
$ **   42 x  
$ **   44 Exit  
$ **  
$ **  
$ ** Unique Set 3:  (Edit Menu)  
$ **  
$ **   50 U  
$ **   52 Undo  
$ **   54 t  
$ **   56 Cut Area  
$ **   58 C  
$ **   60 Copy Area  
$ **   62 P  
$ **   64 Paste Area  
$ **  
$ **        Unique Set 3a:  (Rotate Sub-Menu)  
$ **        68 L  
$ **        70 Left  
$ **        72 R  
$ **        74 Right  
$ **   76 R  
$ **   78 Rotate Area  
$ **  
$ **        Unique Set 3b:  (Flip Sub-Menu)  
$ **        82 V  
$ **        84 Vertical  
$ **        86 H  
$ **        88 Horizontal  
$ **   90 F  
$ **   92 Flip Area  
$ **   94 S  
$ **   96 Scale Area  
$ **   98 z  
$ **   100 Resize Icon...  
$ **   102 A  
$ **   104 Add Hot Spot  
$ **   106 D  
$ **   108 Delete Hot Spot  
$ **   110 G  
$ **   112 Grab Screen Image  
$ **   114 e  
$ **   116 Clear Icon  
$ **  
$ **  
$ ** Unique Set 4:  (Options Menu)  
$ **  
$ **   122 V  
$ **   124 Visible Grid  
$ **  
$ **        Unique Set 4a:  (Output Sub-Menu)  
$ **        128 B  
$ **        130 XBM  
$ **        134 P  
$ **        136 XPM  
$ **   138 O  
$ **   140 Output Format  
$ **   160 M  
$ **   162 Magnification  
$ **  
$ **  
$ ** Unique Set 5:  (Help Menu)  
$ **  
$ **   168 I  
$ **   170 Introduction...  
$ **   172 T  
$ **   174 Tasks...  
$ **   176 R  
$ **   178 Reference...  
$ **   180 O  
$ **   182 On Item  
$ **   188 U  
$ **   190 Using Help...  
$ **   192 V  
$ **   194 Version...  
$ **  
