$ $XConsortium: dttypes.msg /main/2 1996/07/24 18:51:36 drk $
$quote "

$set 1

1 "Dttype"
$ Do not Translate  

2 "Dttype"
$ Do not Translate  

3 "Incipere totum non potest\n"

4 "NULL"
$ this should mean a "Empty string".  

5 "=============== %s ===============\n"
$ Do not Translate  

6 "\0"
$ Do not Translate  

7 "%s\n"
$ Do not Translate  

8 ""
$ Do not Translate  

9 "oneratus ex %s\n"

10 "Ignotus"

11 "\t%s"
$ Do not Translate  

12 "\0"
$ Do not Translate  

13 " :\t%s"
$ Do not Translate  

14 "\0"
$ Do not Translate  

15 "\n"
$ Do not Translate  

16 "-db"
$ Do not Translate  

17 "-w"
$ Do not Translate  

18 "-l"
$ Do not Translate  

19 "rec_info"
$ Do not Translate  

20 "rec_name"
$ Do not Translate  

21 "fld_name"
$ Do not Translate  

22 "fld_value"
$ Do not Translate  

23 "all"
$ Do not Translate  

24 "error = %o, %s\n"
$ Translate "error" only  

25 "Syntaxis:  dttypes [-help]\n\
\tdttypes [-type nomen_scapi]\n\
\tdttypes [-db rec_dat] [-w [rec_name rat_enu] [fld_nom rat_enu]\n\
\t\t\t[fld_value rat_enu]]\n\
\t\t[-l [rec_nom] [rec_perc] [fld_name rat_enu] [fld_value]]\n"
$ Translate only the following: "filename" "database" "regexp"  

26 "-type"
$ Do not Translate  

27 "%s generem %s habet\n"

28 "$"
$ Do not Translate  

29 "--------------------- %s ----------------\n"
$ Do not Translate  

30 "Receptaculum datorum vitiosum\n"

31 "Argument vitiosus\n"

32 "zona rec_info vitiosa in optione -w\n"
$ do not translate "rec_info" or "-w"  

33 "Optionem in -w vel -l invenire non potest\n"
$ do not translate "-w" or "-l"  

34 "Optio ignota\n"

35 "-help"
$ Do not Translate  

36 "error in enuntiatione rationali %s\n"
$ We translate Regular Expression into Enuntiatio Rationalis
$ which is litterally rational expression following the french 
$ language. 
