$ $XConsortium: dtudcfonted.msg
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtudcexch.msg
$ **
$ **  Project:     Fujitsu DT UDC Exchange
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtudcexch
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1996 Fujitsu Ltd.
$ **

$set 2
$ *****************************************************************************
$ ** _DtMessage set for getbdffn.c
$ *****************************************************************************

2 Sélection du fichier BDF 
4 Le fichier sélectionné existe. L'annuler ?
6 L'ouverture du fichier sélectionné a échoué.

$set 4
$ *****************************************************************************
$ ** _DtMessage set for selectx.c
$ *****************************************************************************

2 Hic typus nullam litteram definitam ab usore continet.
4 Aperire typum selectum non potest. Licentiam legendi scapum typi non habet aut forma scapi vitiosa est.
6 Programma LDU altera jam utitur hunc scapum typi. 
8 Nullus typus
10 Aperire
12 Rescindere
14 Utilitaire d'échange de données UDC
16 Seligere res
18 - Jeu de code :
20 -   Style :
22 -   Latitudo :
24 -  Altitudo :

$set 6
$ *****************************************************************************
$ ** _DtMessage set for selectxlfd.c
$ *****************************************************************************

2 Voulez-vous interrompre l'échange UDC ?
4 Nulla LDU in hoc scapo adest.
6 Nomen XLFD selectus non est
8 Aperire scapum typorum non potest
10 Programma LDU altera jam utitur scapum typorum.

$set 8
$ *****************************************************************************
$ ** _DtMessage set for udcexc.c
$ *****************************************************************************

2 Utilitaire UDC d'échange de données
4 Une erreur fatale a eu lieu.
6 Impossible d'ouvrir le fichier de polices.
8 Impossible de lire le fichier de polices.
10 La mémoire est épuisée.
12 Une erreur fatale a eu lieu.
14 Le fichier de polices spécifié n'existe pas.
16 Ce n'est pas une police pcf ou snf.
18 Impossible d'ouvrir le fichier de liste de polices.
20 Le format du fichier de liste de polices est incorrect.
22 Les descriptions du fichier de liste de polices sont incorrectes.
24 Le format du fichier de liste de polices est incorrect.
26 Impossible d'ouvrir le fichier rep. de polices.
28 Impossible de lire le fichier rep. de polices
30 Impossible de lire les propriétés des polices.
32 Impossible d'obtenir la propriété de FONT.
34 Impossible d'obtenir la propriété de FAMILY_NAME.
36 Ce fichier de police est en cours d'utilisation dans une autre application.
38 Impossible de verrouiller le fichier de polices.
40 Impossible de déverrouiller le fichier de polices.
42 Im[possible d'obtenir l'information de verrou du fichier de polices.
44 Impossible de trouver le fichier de polices spécifié.
46 Impossible de lire la base de données NLS.
48 Impossible d'obtenir les noms de charset de la base de données NLS.
50 Le nom charset n'est pas défini dans la base de données NLS.
52 La police spécifiée n'a pas été ouverte.
54 Une erreur fatale a eu lieu.
56 Nomen XLFD           :
58 Typus initii (nomen XLFD)  :
60 Zone de code UDC      :
62 Style              :
64 Taille (taille des lettres) :
66 Aperire
68 Rescindere
70 Profecto
72 Rescindere
74 Copier le code d'origine(hex)  :
76 Copier le code de destination(hex) :
78 Copiare
80 Recouvrir
82 fonction exporter
84 fonction importer
86 Rescindere

$set 10
$ *****************************************************************************
$ ** _DtMessage set for udcexp.c
$ *****************************************************************************

2 La création du fichier BDF a échoué
4 Aucun index sélectionné
6 Profecto
8 Annulerl
10 index de glyphes

$set 12
$ *****************************************************************************
$ ** _DtMessage set for udcexp.c
$ *****************************************************************************

2 Impossible d'ajouter les images glyphes de ce fichier BDF à la police.
4 L'ouverture de la police sélectionnée a échoué. Vous n'avez pas d'autorisation d'accès au fichier de polices ou le format est incorrect.
6 Une ou plusieurs images glyphes seront écrasées. Ecraser ?
8 L'ouverture de la police sélectionnée a échoué. Vous n'avez pas d'autorisation d'accès au fichier de polices ou le format est incorrect.
10 Impossible d'ajouter les images glyphes de ce fichier BDF à la police.
12 L'enregistrement du fichier de polices a échoué.
