$   
$ +SNOTICE  
$   
$  $XConsortium: MotifApp.msg /main/5 1996/10/19 15:26:10 rws $  
$   
$  RESTRICTED CONFIDENTIAL INFORMATION:  
$   
$  The information in this document is subject to special  
$  restrictions in a confidential disclosure agreement between  
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this  
$  document outside HP, IBM, Sun, USL, SCO, or Univel without  
$  Sun's specific written approval.  This document and all copies  
$  and derivative works thereof must be returned or destroyed at  
$  Sun's request.  
$   
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.  
$   
$ +ENOTICE  
$   

$quote "

$set 1
1 "Num vis jubere istium mandatum ?"
2 "Ita"
3 "Relinquere"
4 "Versio programmae cursualis"
5 "Versio programmae cursualis"
6 "Debes seligere partem in fenestram.\n"
7 "Programma cursualis - Adjumentum"
8 "Programma cursualis - Adjumentum"
9 "Visne claudere hoc indicem ?"
10 "Non potes relinquere hoc mandatum. Visne continuare ?"

11 "Aspicere indices et scapos absconditos"
$ /* NL_COMMENT
$  * This message replaces messages 7 and 8.
$  */
12 "Programma cursualis : Adjumentum"

$set 2        Redefine set#
1 "Error selectionem, continuare non potest.\n"
2 "Selectio obstata a usore.\n"
