\" <!-- $XConsortium: ch01.sgm /main/2 1996/12/17 15:35:57 rws $ -->
\" <!-- (c) Copyright 1996 Digital Equipment Corporation. -->
\" <!-- (c) Copyright 1996 Hewlett-Packard Company. -->
\" <!-- (c) Copyright 1996 International Business Machines Corp. -->
\" <!-- (c) Copyright 1996 Sun Microsystems, Inc. -->
\" <!-- (c) Copyright 1996 Novell, Inc. -->
\" <!-- (c) Copyright 1996 FUJITSU LIMITED. -->
\" <!-- (c) Copyright 1996 Hitachi. -->
.TL
 D\*'emarrage
.LP
 Le Common Desktop Environment vous fournit une collection standard de
documents en ligne traitant des divers composants CDE et Motif. Le Bureau
CDE inclut le Gestionnaire des informations qui vous permettra d'acc\*'eder,
de lire et de proc\*'eder \*`a des recherches dans cette documentation.
Le Gestionnaire des informations permet \*'egalement d'acc\*'eder
aux documents en ligne propos\*'es par d'autres applications install\*'ees
sur votre bureau.
 Le reste de ce chapitre d\*'ecrit:
.IP -
 Organisation de l'information
.IP -
 D\*'emarrer le Gestionnaire des informations
.IP -
 Obtenir de l'aide
.IP -
 Utiliser des raccourcis clavier
.NH 1 
Organisation de l'information
.XS
biblioth\*`eques d'informations
.XE
.XS
organisation
.XE
.PP
 Lorsque vous consultez des informations \*`a l'aide du Gestionnaire
des informations, vous parcourez en fait une \fB biblioth\*`eque
d'informations\fR  (\*'egalement appel\*'ee "infolib"). Une
biblioth\*`eque d'informations est divis\*'ee en un ou plusieurs \fB 
rayons\fR . Sur chaque rayon, vous trouverez un ou plusieurs \fB 
livres\fR  qui contiennent la plupart des \*'el\*'ements que
vous vous attendriez \*`a trouver normalement dans un livre imprim\*'e.
 A l'instar d'un livre imprim\*'e, un livre en ligne contient des \fB 
sections\fR  rec\*`elant principalement du texte mais \*'egalement
des objects graphiques et des tables. La liste (table des mati\*`eres)
d'un livre \*'enum\*`ere toutes les sections que contient ce dernier.
*
.FS
* 
 Plusieurs biblioth\*`eques d'informations peuvent \*^etre disponibles
sur votre syst\*`eme.
.FE
 
 La figure suivante illustre la structure d'une biblioth\*`eque d'informations.
Biblioth\*`eque d'informations
.PSPIC "./graphics/infolib1.ps"
.NH 1 
D\*'emarrer le Gestionnaire des informations
.XS
Gestionnaire des informations
.XE
.XS
d\*'emarrer
.XE
.PP
 Lancez le Gestionnaire des informations d'une des mani\*`eres suivantes
:
.IP -
 Cliquez sur l'objet de commande Gestionnaire des informations
dans le Tableau de bord.
.PSPIC "./graphics/fpico.eps"
.IP -
 Cliquez sur l'ic\*^one Gestionnaire des informations dans
le panneau secondaire du Gestionnaire des informations.
.PSPIC "./graphics/infosub.eps"
.IP -
 Faites glisser-d\*'eposez une ic\*^one Biblioth\*`eque
d'informations (repr\*'esent\*'ee dans la fen\*^etre du Gestionnaire
de fichiers) sur le dispositif de commande Gestionnaire des informations dans
le Tableau de bord.
.PSPIC "./graphics/ilibico.eps"
.IP -
 Entrez la commande \fC dtinfo\fR  \*`a partir
de la fen\*^etre Terminal.
 Lors de son d\*'emarrage, le Gestionnaire des informations affiche
la fen\*^etre Liste de livres. Comme l'indique l'illustration suivante,
la fen\*^etre Liste de livres \*'enum\*`ere les biblioth\*`eques
d'informations disponibles.
Fen\*^etre Liste de livres
.PSPIC "./graphics/bklist.eps"
 Les composants des biblioth\*`eques d'informations sont affich\*'es
de mani\*`ere hi\*'erarchique pour vous permettre de progresser vers
des \*'el\*'ements d'information de plus en plus petits et sp\*'ecifiques.
La structure hi\*'erarchique consiste en une arborescence de rayons, de
livres, de chapitres et de sections.
.IP -
 Pour ouvrir un article quelconque de la hi\*'erarchie,
cliquez sur la fl\*`eche vers la droite qui lui est associ\*'ee. Le
Gestionnaire des informations agrandit l'article pour en afficher le contenu.
.IP -
 Pour refermer un article (chapitre, livre, rayon), cliquez
sur la fl\*`eche vers le bas qui se trouve juste \*`a c\*^ot\*'e.
Le Gestionnaire des informations r\*'eduit l'article et supprime son contenu
de l'affichage.
.IP -
 Pour parcourir une section de livre, s\*'electionnez le
nom de la section puis cliquez sur le bouton Visualiser (Jumelles) de la barre
d'outils ou, plus simplement, cliquez deux fois sur le nom de la section.
Le Gestionnaire des informations ouvre la fen\*^etre de lecture, affichant
le contenu de la section s\*'electionn\*'ee. La figure suivante illustre
le mode d'affichage du texte dans la fen\*^etre de lecture.
Fen\*^etre de lecture
.PSPIC "./graphics/readwin.eps"
 Une section \*'etant affich\*'ee, vous pouvez cliquer sur les
boutons de parcours Section pr\*'ec\*'edente et Section suivante (situ\*'es
sur la barre d'outils) pour vous d\*'eplacer parmi les sections.
.PSPIC "./graphics/brwsbuts.eps"
 Cliquez sur les hyperliens (liens hypertexte affich\*'es en gras
et soulign\*'es) pour passer \*`a d'autres parties du livre.
*
.FS
* 
 Si vous le d\*'esirez, laissez la fen\*^etre Liste de livres
ou la fen\*^etre de lecture ouverte pour faciliter vos acc\*`es aux
diverses sections lors d'une session. Vous pouvez \*'egalement r\*'eduire
ces fen\*^etres.
.FE
 
.NH 2 
Ouvrir une biblioth&egrave;que d'informations
.XS
Gestionnaire des informations
.XE
.XS
d\*'emarrer
par une biblioth\*`eque d'informations sp\*'ecifique
.XE
.XS
Biblioth\*`eque d'informations
.XE
.XS
ouvrir
.XE
.PP
 Lorsque vous l'initialisez, le Gestionnaire des informations ou une
ou plusieurs biblioth\*`eques d'informations par d\*'efaut. Si la
biblioth\*`eque d'informations d\*'esir\*'ee ne figure pas dans
la collection par d\*'efaut, indiquez au Gestionnaire des informations
d'initialiser et d'ouvrir la biblioth\*`eque d'une des mani\*`eres
suivantes:
.IP -
 Faites glisser l'ic\*^one de la biblioth\*`eque d'informations
de la fen\*^etre du Gestionnaire de fichiers vers l'objet de commande Gestionnaire
des informations dans le Tableau de bord.
.IP -
 Cliquez deux fois sur l'ic\*^one de la biblioth\*`eque.
.IP -
 Entrez la commande \fC dtinfo\fR  \*`a partir
de la fen\*^etre Terminal et sp\*'ecifiez le chemin d'acc\*`es
\*`a la biblioth\*`eque pour l'option \fC -l\fR .
 Si le Gestionnaire des informations tourne d\*'ej\*`a, chargez
une biblioth\*`eque d'informations en faisant glisser son ic\*^one
dans la fen\*^etre Liste de livres ou dans la fen\*^etre de lecture.
Vous pouvez \*'egalement charger une biblioth\*`eque d'informations
en cliquant sur le bouton <comment>$$$ Traduire</comment>Charger biblinfo
ou en choisissant Ajouter sur le menu <comment>$$$ Traduire</comment>Book
List Edit.
.NH 1 
Quitter le Gestionnaire des informations
.XS
Gestionnaire des informations
.XE
.XS
quitter
.XE
.PP
 Pour quitter le Gestionnaire des informations:
.IP -
 A partir de la fen&ecirc;tre Liste de livres, choisissez
Quitter sur le menu Fichier.
.IP -
 A partir de la fen&ecirc;tre de lecture, choisissez Quitter
sur le menu Explorateur.
 Vous pouvez quitter l'une ou l'autre de ces fen\*^etres en cliquant
deux fois sur le bouton de menu Fen\*^etre (dans le coin sup\*'erieur
gauche).
.NH 1 
Obtenir de l'aide
.XS
Gestionnaire
des informations
.XE
.XS
aide
.XE
.XS
aide
.XE
.PP
 Obtenez de l'aide d'une des mani\*`eres suivantes :
.XS
choisir
.XE
.XS
aide
.XE
.IP -
 Appuyez sur F1 ou sur la touche Aide.
.XS
F1, touche
.XE
.XS
Aide, touche
.XE
.IP -
 Choisissez un \*'el\*'ement sur le menu Aide du Gestionnaire
des informations.
.IP -
 Cliquez sur le bouton Aide \*`a partir d'une bo\*^ite
de dialogue.
 La mani\*`ere la plus rapide et ais\*'ee d'acc\*'eder \*`a
l'aide consiste \*`a actionner la touche F1. Lorsque vous appuyez sur
F1, le Gestionnaire des informations affiche la rubrique d'aide relative \*`a
l'activit\*'e en cours.
 Certains claviers incluent une touche Aide d\*'edi\*'ee qui
remplacera peut-\*^etre la touche F1.
.NH 2 
Le menu Aide
.XS
Aide, menu
.XE
.PP
 Le Gestionnaire des informations propose un menu Aide permettant d'obtenir
des types d'aide sp\*'ecifiques.
 .PSPIC "./graphics/helpmenu.eps"
.TS
center,box; 
l l.
 Introduction	Affiche des informations g\*'en\*'erales sur les fonctionnalit\*'es du Gestionnaire des informations.	
 T\*^aches	Propose des consignes d'utilisation du Gestionnaire des informations.
 R\*'ef\*'erence	Affiche de br\*`eves informations sur les composants du Gestionnaire des informations.
 Sur l'\*'el\*'ement	 Transforme le pointeur en point d'interrogation.
	Cliquez le point d'interrogation sur un \*'el\*'ement pour en afficher
la description.
.XS
point d'interrogation, pointeur
.XE
 Utiliser l'aide	Propose des informations sur l'exploitation de l'utilitaire d'aide.
 A propos du Gestionnaire des informations	Affiche des
	informations sur la version et les droits de reproduction du Gestionnaire des informations.
.TE
.NH 2 
Messages QuickInfo
.XS
QuickInfo,
messages
.XE
.PP
.XS
messages
.XE
.XS
QuickInfo
.XE
 Les messages QuickInfo consistent en de br\*`eves descriptions des
composants de fen\*^etre. Lorsque vous placez le pointeur sur un composant
de fen\*^etre, le message QuickInfo de ce dernier appara\*^it dans la
zone de message. Le message d\*'ecrit le composant et explique son utilisation.
Par exemple, si vous placez le pointeur sur le bouton Section pr\*'ec\*'edente
(Fl\*`eche vers le haut) de la barre d'outils de la fen\*^etre de lecture,
la zone de message affiche:
 \fC Allez vers la section du document\fR 
.NH 2 
Utiliser les fen\*^etres d'aide
.XS
fen\*^etres
.XE
.XS
Aide
.XE
.XS
Aide
.XE
.XS
fen\*^etres
.XE
.PP
 Lorsque vous acc\*'edez \*`a l'aide, le Gestionnaire des informations
affiche une fen\*^etre contenant le texte d'aide requis. Pour obtenir des
informations compl\*'ementaires sur une t\*^ache d\*'ecrite, cliquez
sur le bouton <comment>$$$ Traduire</comment>Autres...<?Pub Caret> Pour obtenir
de l'aide sur l'exploitation de l'utilitaire d'aide, cliquez sur le bouton
Aide. Pour refermer une fen\*^etre d'aide, cliquez sur le bouton Fermer.
.NH 1 
Utiliser des raccourcis clavier
.XS
clavier
.XE
.XS
raccourcis
.XE
.PP
 Le rectangle en surbrillance d\*'esigne l'\*'el\*'ement
de fen\*^etre, de menu ou objet de commande qui sera affect\*'e par
votre entr\*'ee. Pour activer un \*'el\*'ement de menu ou un objet
de comande s\*'electionn\*'e (tel qu'un bouton), appuyez sur la barre
d'espacement.
 Vous pr\*'ef\*'ererez probablement appuyer sur F10 pour positionner
le rectangle de surbrillance dans la barre de menu. Ceci vous permettra de
naviguer d'un menu \*`a l'autre \*`a l'aide des touches fl\*'ech\*'ees
ou en appuyant sur la premi\*`ere lettre du nom de menu.
.bp
<?Pub *0000018752>
\" <!-- $XConsortium: ch02.sgm /main/2 1996/12/17 15:36:07 rws $ -->
\" <!-- (c) Copyright 1996 Digital Equipment Corporation. -->
\" <!-- (c) Copyright 1996 Hewlett-Packard Company. -->
\" <!-- (c) Copyright 1996 International Business Machines Corp. -->
\" <!-- (c) Copyright 1996 Sun Microsystems, Inc. -->
\" <!-- (c) Copyright 1996 Novell, Inc. -->
\" <!-- (c) Copyright 1996 FUJITSU LIMITED. -->
\" <!-- (c) Copyright 1996 Hitachi. -->
.TL
 Lire les livres
.LP
 Plusieurs m\*'ethodes permettent de vous d\*'eplacer dans une
biblioth\*`eque d'informations. La mani\*`ere la plus simple de d\*'emarrer
est de consid\*'erer une biblioth\*`eque d'informations comme une
collection de livres en ligne. Les livres en ligne pr\*'esentent des caract\*'eristiques
similaires \*`a celles des livres imprim\*'es traditionnels. Par exemple,
les livres en ligne sont structur\*'es en chapitres et sections et contiennent
des tables des mati\*`eres. Par contre, les livres en ligne proposent
\*'egalement des fonctionnalit\*'es, telles que les liens hypertexte,
que n'offrent pas les livres imprim\*'es traditionnels.
 Ce chapitre d\*'ecrit les principes fondamentaux de la lecture des
livres en ligne et explique comment:
.IP -
 Utiliser les fen\*^etres du Gestionnaire
.IP -
 Lire un livre dans l'ordre des sections
.NH 1 
Utiliser les fen\*^etres du Gestionnaire
des informations
.XS
fen\*^etres
.XE
.XS
utiliser
.XE
.PP
 Lorsque vous l'initialisez, le Gestionnaire des informations affiche
la fen\*^etre Liste de livres qui \*'enum\*`ere les biblioth\*`eques
d'information r\*'esidant sur le syst\*`eme. La fen\*^etre Liste
de livres permet un acc\*`es traditionnel aux informations \*`a consulter
dans le Gestionnaire des informations. A partir de la Liste de livres, ouvrez
des fen\*^etres de lecture affichant le contenu des livres d'une biblioth\*`eque
d'informations. Pour ne jamais vous \*'egarer dans une biblioth\*`eque
d'informations, vous pouvez configurer la Liste de livres de mani\*`ere
\*`a enregistrer un historique de vos d\*'eplacements. L'\*'ecran
Liste de livres permet \*'egalement d'imprimer des sections de livres.
 La figure suivante repr\*'esente la fen\*^etre Liste des livres
du Gestionnaire des informations.
Fen\*^etre Liste des livres
.PSPIC "./graphics/bklist1.eps"
 Cliquez deux fois sur le titre de la section \*`a lire pour indiquer
au Gestionnaire des informations d'ouvrir une fen\*^etre de lecture affichant
le texte de la section s\*'electionn\*'ee. A partir de la fen\*^etre
de lecture, vous pouvez lire du texte et acc\*'eder \*`a toutes les
autres fonctions du Gestionnaire des informations. Plus sp\*'ecifiquement,
il vous est loisible de consulter du texte et des \*'el\*'ements graphiques,
d'imprimer, de proc\*'eder \*`a des recherches, d'utiliser des signets
et des notes, de d\*'efinir des pr\*'ef\*'erences et d'acc\*'eder
\*`a l'aide.
 La ligure suivante repr\*'esente la fen\*^etre de lecture du
Gestionnaire des informations.
Fen\*^etre de lecture
.PSPIC "./graphics/readwin1.eps"
 Bien que la plupart des fonctions des fen\*^etres du Gestionnaire
des informations soient identiques \*`a celles des autres fen\*^etres
de l'environnement CDE, les sections suivantes proposent certains conseils
d'utilisation des fen\*^etres du Gestionnaire des informations:
.IP -
 Configurer la Liste de livres de mani\*`ere
.IP -
 Utiliser plusieurs fen\*^etres
.IP -
 Redimensionner une fen\*^etre de lecture
.IP -
 Dupliquer une fen\*^etre de lecture
.IP -
 Fermer une fen"INFOUG.Rdbooks.mkr.7"amp;ecirc;tre de lecture
.NH 2 
Configurer la Liste de livres de mani\*`ere
\*`a maintenir un historique
.XS
Liste de livres
.XE
.XS
configurer de mani\*`ere \*`a maintenir un historique
.XE
.XS
fen\*^etres
.XE
.XS
configurer
la Liste de livres de mani\*`ere \*`a maintenir un historique
.XE
.PP
 Pour d\*'eterminer rapidement o\*`u vous vous trouvez dans l'arborescence
de la biblioth&egrave;que d'informations, vous pouvez configurer la Liste
des livres de mani\*`ere \*`a maintenir automatiquement un historique
de vos d\*'eplacements.
 Lorsque l'historique automatique est activ\*'e, une ic\*^one
en forme de doigt dans la fen\*^etre Liste des livres pointe vers le titre
de la section que vous lisez actuellement. A mesure que vous vous d\*'eplacez
dans la biblioth&egrave;que d'informations, la Liste des livres s'actualise
automatiquement pour indiquer votre position actuelle.
 Si la section en cours est subordonn\*'ee \*`a une section non
\*'etendue dans la Liste des livres, l'ic\*^one en forme de doigt est
\*Q vide\*U  et pointe vers le titre de la section parent.
 Pour activer/d\*'esactiver l'historique automatique, choisissez
Historique automatique sur le menu Options de la fen\*^etre Liste des livres.
L'historique automatique est activ\*'e si vous remarquez une coche \*`a
c\*^ot\*'e de l'option Historique automatique.
 Veuillez remarquer que l'ic\*^one d'historique appara\*^it uniquement
lorsqu'une fen\*^etre de lecture est ouverte.
.NH 2 
Utiliser plusieurs fen\*^etres
.XS
fen\*^etres
.XE
.XS
ancrer
.XE
.XS
fen\*^etres
.XE
.XS
utiliser plusieurs
.XE
.PP
 Le Gestionnaire des informations vous permet d'utiliser plusieurs fen\*^etres
de lecture \*`a la fois. Vous pouvez par exemple conserver le texte d'une
fen\*^etre tout en lisant les sections d'une autre fen\*^etre. Pour
ce faire, cliquez sur la punaise (plus pr\*'ecis\*'ement une \fI pushpin\fR ) de la barre d'outils de la fen\*^etre de lecture. Le
fait de cliquer sur cette ic\*^one vous permet d'alterner entre les modes
ancr\*'ee et non ancr\*'ee.
 Si une fen\*^etre est \*Q ancr\*'ee\*U , le Gestionnaire
des informations ouvre une autre fen\*^etre de lecture pour la section
suivante \*`a laquelle vous acc\*'edez. Si une fen\*^etre n'est
pas ancr\*'ee, le Gestionnaire des informations remplace le texte de la
fen\*^etre en cours par celui de la nouvelle section.
.XS
pushpin
.XE
 Si une fen\*^etre est \*Q ancr\*'ee\*U , la \fI pushpin\fR  appara\*^it dans le coin sup\*'erieur droit, accompagn\*'ee
d'une coche.
.PSPIC "./graphics/pushpin.eps"
*
.FS
* 
 Vous pouvez \*'egalement ancrer des fen\*^etres R\*'esultats
de la recherche. Si vous ancrez une fen\*^etre R&eacute;sultats de
la recherche, le Gestionnaire des informations ne remplace pas les r\*'esultats
de la premi\*`ere recherche par ceux des recherches suivantes. Au contraire,
les nouveaux r&eacute;sultats de recherche apparaissent dans des fen\*^etres
R\*'esultats de la recherche s\*'epar\*'ees.
.FE
 
 Choisissez Pr\*'ef\*'erences sur le menu Options pour sp\*'ecifier
si toutes les nouvelles fen\*^etres de lecture seront ancr\*'ees ou
non, par d\*'efaut. Pour gagner de l'espace \*`a l'\*'ecran, il
convient probablement de limiter le nombre de fen\*^etres utilis\*'ees
simultan\*'ement.
 Il se r\*'ev\*'elera probablement utile d'ancrer la fen\*^etre
Index si vous pr\*'evoyez de suivre plusieurs liens.
.NH 2 
Redimensionner une fen\*^etre de lecture
.XS
fen\*^etres
.XE
.XS
fen\*^etre de lecture
.XE
.XS
redimensionner
.XE
.XS
fen\*^etre
de lecture
.XE
.XS
redimensionner
.XE
.PP
 Pour modifier la taille d'une fen\*^etre de lecture, utilisez la
souris pour faire glisser et d\*'eplacer les bords de la fen\*^etre,
ou utilisez le bouton Agrandir dans le coin sup\*'erieur droit du cadre
de la fen\*^etre. Les nouvelles dimensions de la fen\*^etre resteront
en<?Pub Caret> vigueur pour le reste de votre session Gestionnaire des informations
ou jusqu'\*`a ce que vous les modifiiez. Lorsque vous redimensionnez une
fen\*^etre de lecture, le texte s'ajuste automatiquement \*`a la nouvelle
taille de fen\*^etre.
 Pour d\*'efinir la taille par d\*'efaut de la fen\*^etre
de lecture, choisissez Pr\*'ef\*'erences d'exploration sur le menu
Options et sp\*'ecifiez la nouvelle taille de G\*'eom\*'etrie
de l'explorateur. Pour obtenir des informations compl\*'ementaires sur
la sp\*'ecification de pr\*'ef\*'erences, consultez la section \" <!--XRef
content: 'Personnaliser le Gestionnaire des informations
Personnaliser le Gestionnaire des informations.
.NH 2 
Dupliquer une fen\*^etre de lecture
.XS
fen\*^etres
.XE
.XS
fen\*^etre de lecture
.XE
.XS
dupliquer
.XE
.XS
fen\*^etre
de lecture
.XE
.XS
dupliquer
.XE
.PP
 Dans certaines circonstances, il sera peut-\*^etre n\*'ecessaire
d'afficher simultan\*'ement deux parties (ou plus) d'une longue section.
Pour ce faire, dupliquez la fen\*^etre de lecture.
 Pour dupliquer une fen\*^etre de lecture, s\*'electionnez Nouvelle
fen\*^etre sur le menu Explorateur. Le Gestionnaire des informations ouvre
une autre fen\*^etre de lecture affichant la m\*^eme section. Dans cette
seconde fen\*^etre, passez \*`a une partie de document diff\*'erente
de celle de la premi\*`ere fen\*^etre.
.NH 2 
Fermer une fen&ecirc;tre de lecture
.XS
fen\*^etre de lecture
.XE
.XS
fermer
.XE
.XS
fen\*^etres
.XE
.XS
fen\*^etre de lecture
.XE
.XS
fermer
.XE
.PP
 Pour ferner une fen\*^etre de lecture, choisissez Fermer sur le menu
Explorateur. La fermeture d'une fen\*^etre de lecture n'entra\*^ine
pas votre sortie du Gestionnaire des informations.
 Pour quitter le Gestionnaire des informations, choisissez Quitter sur
le menu Explorateur.
.NH 1 
Lire un livre dans l'ordre des sections
.XS
naviguer
.XE
.XS
lire dans l'ordre des sections
.XE
.PP
 La structure traditionnelle des livres du Gestionnaire des informations
sugg\*`ere une mani\*`ere bien connue de vous d\*'eplacer dans
une biblioth\*`eque d'informations. Vous pouvez consulter les livres \*`a
l'aide d'utilitaires tels que la Table des mati\*`eres. Vous pouvez \*'egalement
passer d'une section \*`a la suivante dans leur ordre d'insertion.
 Pour parcourir un livre dans l'ordre sugg\*'er\*'e des sections,
cliquez sur les boutons Section pr\*'ec\*'edente et Section suivante
(situ\*'es sur la barre d'outils de la fen&ecirc;tre de lecture) pour
passer, respectivement, aux sections ant\*'erieures ou ult\*'erieures.
.PSPIC "./graphics/brwsbuts.eps"
 La fl\*`eche vers le haut vous fait passer \*`a la section pr\*'ec\*'edente.
Si vous vous trouvez d\*'ej\*`a dans la premi\*`ere section, cette
fl\*`eche n'est pas disponible.
 La fl\*`eche vers le bas vous am\*`ene \*`a la section suivante.
Si vous vous trouvez d\*'ej\*`a dans la derni\*`ere section, cette
fl\*`eche est estomp\*'ee.
 Pour pr\*'evisualiser la section suivante ou pr\*'ec\*'edente,
placez le pointeur sur une des fl\*`eches de parcours Section pr\*'ec\*'edente
ou Section suivante. Ensuite, cliquez tout en maintenant le bouton de la souris.
Le Gestionnaire des informations affiche le titre de la section suivante ou
pr\*'ec\*'edente dans la zone de message. Si vous pr\*'ef\*'erez
ne pas aller \*`a la section indiqu\*'ee, d\*'eplacez le pointeur
de la fl\*`eche avant de rel\*^acher le bouton de la souris.
 D\*`es que vous vous trouvez dans une section, d\*'eplacez-vous
dans celle-ci \*`a l'aide de la barre de d\*'efilement, des touches
Page pr\*'ec. et Page suiv., ou des Fl\*`eches vers le haut et vers
le bas.
.bp
<?Pub *0000017568>
\" <!-- $XConsortium: ch03.sgm /main/2 1996/12/17 15:36:15 rws $ -->
\" <!-- (c) Copyright 1996 Digital Equipment Corporation. -->
\" <!-- (c) Copyright 1996 Hewlett-Packard Company. -->
\" <!-- (c) Copyright 1996 International Business Machines Corp. -->
\" <!-- (c) Copyright 1996 Sun Microsystems, Inc. -->
\" <!-- (c) Copyright 1996 Novell, Inc. -->
\" <!-- (c) Copyright 1996 FUJITSU LIMITED. -->
\" <!-- (c) Copyright 1996 Hitachi. -->
.TL
 Naviguer dans le Gestionnaire des informations
.LP
 Outre la structure de livre traditionnelle, il existe d'autres mani\*`eres
de naviguer dans une biblioth\*`eque d'informations. Vous pouvez, par
exemple, lire les livres d'une biblioth\*`eque en suivant les \fB 
liens\fR  menant \*`a des informations connexes. Vous pouvez aussi
utiliser les fonctionnalit\*'es Historique et Carte pour localiser les
informations d\*'esir\*'ees.
 Ce chapitre offre des informations sur:
.IP -
 Identifier votre position actuelle
.IP -
 Utiliser les points d'mplantation
.IP -
 Suivre les liens
.IP -
 Retracer vos pas
.IP -
 Visualiser les sections pr\*'ec\*'edentes
.IP -
 Naviguer \*`a l'aide de la carte graphique
 Il est \*'egalement possible de rechercher rapidement des informations
sur un \*'el\*'ement sp\*'ecifique. Consultez la section \" <!--Original
XRef content: 'Rechercher des informationsRechercher des informations
pour obtenir des instructions compl\*'ementaires sur le lancement d'une
recherche, la formulation des crit\*`eres de recherche et la d\*'efinition
de l'\*'etendue de la recherche.
.NH 1 
Identifier votre position actuelle
.XS
position
.XE
.XS
actuelle, identifier
.XE
.PP
 Les liens hypertexte vous permettent de vous d\*'eplacer rapidement
et ais\*'ement d'une section \*`a une autre, voire m\*^eme d'un
livre \*`a un autre. Au fil de vos d\*'eplacements dans un livre ou
m\*^eme dans toute une biblioth\*`eque, il est relativement facile
de perdre de vue votre position actuelle. Pour identifier rapidement votre
position actuelle, proc\*'edez de la mani\*`ere suivante:
.IP -
 Points d'implantation. VoirUtiliser les points d'mplantation.
.IP -
 Historique automatique (la Liste de livres). Voir 
Configurer la Liste de livres de mani\*`ere.
.IP -
 Affichage de la section pr\*'ec\*'edente (l'Historique).
Voir Visualiser les sections pr\*'ec\*'edentes.
.IP -
 La carte graphique. Voir Naviguer \*`a l'aide de la carte graphique.
.NH 1 
Utiliser les points d'mplantation
.XS
points d'implantation
.XE
.XS
utiliser
.XE
.PP
 Chaque livre et chaque section de livre est associ\*'ee \*`a
un identificateur unique nomm\*'e \fB point d'implantation\fR .
Le Gestionnaire des informations vous permet d'afficher les points d'implantation
et de les utiliser pour acc\*'eder aux sections qu'ils identifient.
.NH 2 
Afficher les points d'implantation
.XS
Afficher le point d'implantation
.XE
.XS
point d'implantation
.XE
.XS
afficher
.XE
.XS
position
.XE
.XS
afficher le point d'implantation
.XE
.XS
emplacement
.XE
.PP
 Pour afficher le point d'implantation du livre et de la section que
vous visualisez actuellement, choisissez Afficher le point d'implantation
sur le menu Explorateur. Le Gestionnaire des informations affiche le point
d'implantation dans la zone de message au bas de la fen\*^etre.
 Pour retourner \*`a une section par la suite, vous pouvez enregistrer
son point d'implantation puis le sp\*'ecifier \*`a l'aide d'Ouvrir
le point d'implantation.
.NH 2 
Aller aux points d'implantation
.XS
Ouvrir le point d'implantation
.XE
.XS
points d'implantation
.XE
.XS
ouvrir
.XE
.XS
position
.XE
.XS
ouvrir le point d'implantation
.XE
.PP
 Pour retourner \*`a une section dont vous avez pr\*'ec\*'edemment
consult\*'e le point d'implantation \*`a l'aide d'Afficher le point
d'implantation, choisissez Ouvrir le point d'implantation sur le menu Aller.
Le Gestionnaire des informations affiche la bo\*^ite de dialogue suivante
pour vous permettre de sp\*'ecifier le point d'implantation de la section.
Ouvrir le point d'implantation, bo\*^ite
de dialogue
.PSPIC "./graphics/openloca.eps"
 Sp\*'ecifiez le point d'implantation de la section vers laquelle
vous d\*'eplacer.
 Cliquez sur Appliquer pour aller \*`a cette section et laisser la
bo\*^ite de dialogue ouverte; cliquez sur OK pour aller \*`a la section
et refermer la bo\*^ite de dialogue.
.NH 1 
Suivre les liens
.XS
naviguer
.XE
.XS
suivre les liens
.XE
.XS
liens
.XE
.XS
suivre
.XE
.PP
 Dans le Gestionnaire des informations, les liens hypertexte sont repr\*'esent\*'es
par du texte gras, soulign\*'e et color\*'e. Les liens vous permettent
de proc\*'eder \*`a des \*Q sauts\*U  rapides vers
.IP -
 D'autres parties de la section en cours
.IP -
 D'autres sections du m\*^eme livre
.IP -
 D'autres livres de la biblioth\*`eque d'informations
 Pour suivre un lien dans la fen\*^etre de lecture, positionnez le
pointeur sur le texte du lien et cliquez. Pour suivre un lien dans une fen\*^etre
de liste (telle que celle de l'Historique des sections), positionnez le pointeur
sur le lien et cliquez deux fois.
 Lorsque vous suivez un lien \*`a partir d'une fen\*^etre de lecture
non ancr\*'ee, le Gestionnaire des informations remplace la section en
cours par la nouvelle. Si la fen\*^etre de lecture est ancr\*'ee, le
Gestionnaire des informations ouvre une nouvelle fen\*^etre de lecture
pour afficher la nouvelle section.
.NH 2 
Pr\*'evisualiser les destinations des
liens
.XS
liens
.XE
.XS
pr\*'evisualiser les
destinations
.XE
.XS
naviguer
.XE
.XS
pr\*'evisualiser les destinations des liens
.XE
.PP
 A partir de la fen\*^etre de lecture, vous pouvez pr\*'evisualiser
la destination d'un lien avant de d\*'ecider de le suivre. Pour afficher
le titre de la section cible:
.IP \(rh
 Positionnez le pointeur sur le lien.
.IP \(rh
 Appuyez sur le bouton gauche de la souris et maintenez-le
enfonc\*'e. Le Gestionnaire des informations affiche la destination du
lien dans la zone de message du bas de la fen\*^etre.
.IP \(rh
 Pour suivre le lien, rel\*^achez le bouton de la souris.
Si vous d\*'ecidez de ne pas suivre le lien, \*'eloignez le pointeur
du lien avant de rel\*^acher le bouton de la souris.
.NH 1 
Retracer vos pas
.XS
naviguer
.XE
.XS
retracer vos pas
.XE
.PP
 Dans certains cas, vous souhaiterez probablement repasser \*`a une
section consult\*'ee pr\*'ealablement au cours de votre session d'exploration.
Pour revoir des sections ant\*'erieures, choisissez une des m\*'ethodes
suivantes:
.IP -
 La liste Historique des sections. Voir 
Utiliser la liste Historique des sections.
.IP -
 Fl\*`eches de l'Historique. Voir 
Utiliser les fl\*`eches de l'Historique.
.NH 2 
Utiliser la liste Historique des sections
.XS
naviguer
.XE
.XS
\*`a l'aide de la liste Historique
des sections
.XE
.XS
retracer vos pas
.XE
.XS
\*`a l'aide de la liste Historique des sections
.XE
.XS
Historique des sections, liste
.XE
.PP
 Le Gestionnaire des informations affiche l'enregistrement chronologique
de tous vos d\*'eplacements dans les sections visit\*'ees au cours
de la session d'exploration actuelle. Pour v\*'erifier rapidement les
sections d\*'ej\*`a lues, ouvrez la liste Historique des sections,
repr\*'esent\*'ee par la figure suivante.
Liste Historique des sections
.PSPIC "./graphics/histlist.eps"
 La liste Historique des sections inclut chaque section visit\*'ee,
de la plus r\*'ecente \*`a la plus ancienne. Si vous avez consult\*'e
une section plusieurs fois par session, le Gestionnaire des informations ne
la liste qu'une fois.
 Pour utiliser la liste Historique des sections:
.IP \(rh
 Choisissez Historique sur le menu Aller de la fen\*^etre
de lecture. Le Gestionnaire des informations affiche la liste Historique des
sections.
.IP \(rh
 Pour passer \*`a une section de la liste, cliquez deux
fois sur son titre ou affichez ce titre en surbrillance, puis cliquez sur
Afficher. Si la fen\*^etre de lecture n'est pas ancr\*'ee, le Gestionnaire
des informations remplace la section en cours par la nouvelle. Si la fen&ecirc;tre
de lecture est ancr\*'ee, le Gestionnaire des informations ouvre une autre
fen\*^etre de lecture pour afficher la nouvelle section.
 Pour refermer la liste Historique des sections sans passer \*`a
une section pr\*'ealablement visualis\*'ee, cliquez sur Fermer.
.NH 2 
Utiliser les fl\*`eches de l'Historique
.XS
fl\*`eches
.XE
.XS
historique
.XE
.XS
historique, fl\*`eches
.XE
.XS
naviguer
.XE
.XS
avec les fl\*`eches de l'Historique
.XE
.XS
retracer vos pas
.XE
.XS
avec
les fl\*`eches de l'Historique
.XE
.PP
 Vous souhaiterez probablement vous d\*'eplacer vers l'arri\*`ere
ou vers l'avant parmi la s\*'erie de sections pr\*'ealablement consult\*'ees.
Utilisez les fl\*`eches de l'Historique de la fen\*^etre de lecture
pour vous d\*'eplacer parmi les sections d\*'ej\*`a lues, dans
l'ordre de lecture initial. Les fl\*`eches de l'Historique apparaissent
au d\*'ebut de la barre d'outils de la fen\*^etre de lecture, \*`a
gauche des fl\*`eches de parcours normales.
.PSPIC "./graphics/hsarrows.eps"
*
.FS
* 
 Vous pouvez ex\*'ecuter les m\*^emes fonctions en choisissant
les options <comment>nouveau terme</comment>En arri\*`ere et <comment>
nouveau terme</comment>En avant du menu <comment>nouveau terme</comment>Aller.
.FE
 
 Si vous avez consult\*'e plusieurs fois la m\*^eme section au
cours de votre session d'exploration, les fl\*`eches de l'Historique en
feront de m\*^eme.
 La fl\*`eche vers la gauche de l'Historique vous d\*'eplace
en arri\*`ere dans la liste des sections (vers le d\*'ebut); la fl\*`eche
vers la droite vous d\*'eplace vers l'avant (vers la fin de la liste).
 Si vous vous trouvez au d\*'ebut de la liste des sections, les fl\*`eches
vers la gauche ou vers la droite de l'Historique ne sont plus disponibles,
indiquant que vous ne pouvez aller plus dans cette direction.
.NH 1 
Visualiser les sections pr\*'ec\*'edentes
.XS
naviguer
.XE
.XS
avec le bouton de titre de section
.XE
.XS
retracer vos pas
.XE
.XS
avec
le bouton de titre de section
.XE
.XS
section
.XE
.XS
visualiser la pr\*'ec\*'edente
.XE
.XS
sections pr\*'ec\*'edentes
.XE
.XS
visualiser
.XE
.XS
titre de
section, bouton
.XE
.PP
 Il se peut que vous souhaitiez obtenir des informations d'ordre plus
g\*'en\*'eral que celles de la section en cours, ou une meilleure
perspective du niveau des informations \*`a consulter. En d'autres termes,
imaginons que vous souhaitez visualiser la liste des sections pr\*'ec\*'edant
la section en cours dans la structure du livre.
 Pour afficher la liste des sections pr\*'ec\*'edentes, cliquez
sur le bouton de titre de section, juste en dessous de la zone d'affichage.
.PSPIC "./graphics/sectitle.eps"
 Le Gestionnaire des informations affiche la liste des titres de section.
 Vous pouvez remonter dans cette liste jusqu'au nom de la biblioth\*`eque
contenant le livre de la section.
*
.FS
* 
 Les deux \*'el\*'ements sup\*'erieurs de la liste repr\*'esentent
le rayon et la biblioth\*`eque d'informations. N'identifiant ni l'un<?Pub Caret> ni
l'autre une section sp\*'ecifique, ils ne peuvent \*^etre s\*'electionn\*'es.
.FE
 
 Pour passer \*`a une section quelconque de la liste, cliquez sur
son titre. Si la fen\*^etre de lecture n'est pas ancr\*'ee, le Gestionnaire
des informations remplace la section en cours par la nouvelle. Si la fen&ecirc;tre
de lecture est ancr\*'ee, le Gestionnaire des informations ouvre une autre
fen\*^etre de lecture pour afficher la nouvelle section.
 Pour refermer la liste des sections sans passer \*`a une autre section,
cliquez une nouvelle fois sur le bouton de titre de section.
.NH 1 
Naviguer \*`a l'aide de la carte graphique
.XS
carte
.XE
.XS
naviguer avec
.XE
.XS
graphique, carte
.XE
.XS
naviguer
.XE
.XS
\*`a l'aide de la carte graphique
.XE
.PP
 Pour vous orienter dans la structure d'un livre, vous pouvez afficher
une carte graphique de ses sections. La carte constitue une sorte d' \fI arborescence\fR  graphique qui affiche les titres des sections du livre.
La carte facilite la compr\*'ehension de la structure d'ensemble du livre.
Carte graphique
.PSPIC "./graphics/graphmap.eps"
.NH 2 
Ouvrir la carte
.XS
carte
graphique
.XE
.XS
ouvrir
.XE
.PP
 Pour afficher la carte, cliquez sur le bouton Carte graphique de la
barre d'outils de la fen\*^etre de lecture ou choisissez Carte graphique
\*`a partir du menu Fen\*^etres.
.PSPIC "./graphics/gmap.eps"
 Le Gestionnaire des informations ouvre la carte graphique, affichant
le titre de la section en cours et les titres des autres sections du livre.
.NH 2 
Faire un panoramique au travers de la carte
.XS
carte graphique
.XE
.XS
faire un panoramique
.XE
.PP
 Pour afficher les titres de section actuellement invisibles, proc\*'edez
\*`a un panoramique au travers de la carte. Cette fonctionnalit\*'e
est tr\*`es utile: les cartes sont g\*'en\*'eralement trop grandes
pour \*^etre compl\*`etement affich\*'ees.
 La carte graphique contient une \fB case de panoramique\fR 
dans son coin sup\*'erieur gauche, dans laquelle s\*'electionner la
partie de la carte \*`a afficher.
 Pour r\*'ealiser un panoramique au travers d'une carte:
.IP \(rh
 Positionnez le pointeur sur la zone de panoramique de la carte
des sections locales.
.IP \(rh
 Appuyez sur le bouton gauche de la souris et maintenez-le
enfonc\*'e.
.IP \(rh
 Faites glisser la souris de mani\*`ere de mani\*`ere
\*`a afficher la partie de la carte \*`a consulter. Par exemple, d\*'eplacez
la zone de panoramique vers la droite pour afficher les titres dissimul\*'es
par le bord droit de la carte.
*
.FS
* 
 Si vous pr\*'ef\*'erez, vous pouvez ajuster la taille de toute
la carte graphique en redimensionnant la fen\*^etre.
.FE
 
.NH 2 
Aller \*`a une section de la carte
.XS
carte graphique
.XE
.XS
aller \*`a une section
.XE
.PP
 Pour afficher une section repr\*'esent\*'ee sur la carte graphique,
cliquez sur le titre de cette section. Si la fen\*^etre de lecture n'est
pas ancr\*'ee, le Gestionnaire des informations remplace la section en
cours par la nouvelle. Si la fen&ecirc;tre de lecture est ancr\*'ee,
le Gestionnaire des informations ouvre une autre fen\*^etre de lecture
pour afficher la nouvelle section.
.NH 2 
Mettre la carte graphique \*`a jour
.XS
carte
.XE
.XS
mettre \*`a jour
.XE
.PP
 Pour actualiser la carte graphique de mani\*`ere \*`a afficher
votre emplacement actuel dans un livre, cliquez sur le bouton Mise \*`a
jour automatique afin de refl\*'eter votre position chaque fois que vous
vous d\*'eplacez au sein d'un livre, choisissez Pr\*'ef\*'erences
de carte sur le menu Options, puis activez Mise \*`a jour automatique.
.bp
<?Pub *0000023538>
\" <!-- $XConsortium: ch04.sgm /main/2 1996/12/17 15:36:24 rws $ -->
\" <!-- (c) Copyright 1996 Digital Equipment Corporation. -->
\" <!-- (c) Copyright 1996 Hewlett-Packard Company. -->
\" <!-- (c) Copyright 1996 International Business Machines Corp. -->
\" <!-- (c) Copyright 1996 Sun Microsystems, Inc. -->
\" <!-- (c) Copyright 1996 Novell, Inc. -->
\" <!-- (c) Copyright 1996 FUJITSU LIMITED. -->
\" <!-- (c) Copyright 1996 Hitachi. -->
.TL
 Rechercher des informations
.LP
 Lorsque vous avez besoin d'informations sp\*'ecifiques, proc\*'eder
\*`a une r\*'eelle recherche est nettement plus efficace que simplement
explorer. Le Gestionnaire des informations propose une panoplie compl\*`ete
de fonctionnalit\*'es de recherche vous permettant de:
.IP -
 Proc\*'eder \*`a des recherches rapides \*`a l'aide
de simples crit\*`eres de recherche. Voir Rechercher rapidement.
.IP -
 Effectuer des recherches d\*'etaill\*'ees gr\*^ace
\*`a l'Editeur de requ\*^etes. Voir D\*'efinir des recherches d\*'etaill\*'ees.
.IP -
 D\*'efinir l'\*'etendue des recherches de mani\*`ere
\*`a couvrir une seule section, ou des livres et types d'informations
sp\*'ecifiques. Voir D\*'efinir l'\*'etendue des recherches.
.IP -
 Afficher les r\*'esultats de la recherche et lire les
sections contenant des r\*'esultats correspondants. Voir 
Consulter les r\*'esultats de la recherche.
*
.FS
* 
 Pour r\*'eduire la taille de la base de donn\*'ees de recherche,
le Gestionnaire des informations n'effectue pas de recherches sur de nombreux
mots courants tels que: I et R, I mais R, I ou R, I le R, I etc. R
.FE
 
.NH 1 
Rechercher rapidement
.XS
rechercher
.XE
.XS
m\*'ethode rapide
.XE
.XS
recherche rapide
.XE
.PP
 Pour proc\*'eder \*`a une recherche rapide sur un simple mot
ou une phrase, utilisez le champ de recherche rapide au bas de la fen\*^etre
de lecture. Entrez le texte recherch\*'e manuellement ou en affichant
en surbrillance une cha\*^ine de texte existante puis en choisissant l'option
S\*'election sur le menu Rechercher.
Champ de recherche rapide
.PSPIC "./graphics/searchin.eps"
.NH 2 
Lancer une recherche rapide
.XS
recherche rapide
.XE
.XS
lancer
.XE
.XS
lancer
.XE
.XS
recherche rapide
.XE
.PP
 Pour initialiser une recherche \*`a partir du champ de recherche
rapide:
.IP \(rh
 Placez le pointeur dans le champ de recherche rapide et, si
n\*'ecessaire, supprimez le texte existant.
.IP \(rh
 Tapez le texte \*`a rechercher.
 Lorsque vous placez le pointeur dans le champ de recherche rapide, le
bouton Etendue de recherche, \*`a gauche du champ, identifie l'\*'etendue
\*`a utiliser pour la recherche. Si l'\*'etendue indiqu\*'ee est
celle que vous souhaitez utiliser, omettez les \*'etapes 3 et 4. Pour
obtenir des informations sur les \*'etendues de recherches, consultez
la section D\*'efinir l'\*'etendue des recherches.
.IP \(rh
 Cliquez sur le bouton Etendue de recherche. Le Gestionnaire
des informations affiche la liste des \*'etendues de recherche disponibles.
Liste des \*'etendues de recherche
.PSPIC "./graphics/scoplist.eps"
.IP \(rh
 Cliquez sur l'\*'etendue sur laquelle effectuer la recherche.
.IP \(rh
 Appuyez sur la touche Retour pour lancer la recherche.
 Le Gestionnaire des informations affiche les valeurs concordantes dans
la fen\*^etre R\*'esultats de la recherche. Pour passer \*`a une
section contenant une cha\*^ine concordante, cliquez deux fois sur le titre
de la section dans la fen\*^etre R\*'esultats de la recherche.
 Pour cr\*'eer des crit\*`eres de recherche plus d\*'etaill\*'es,
utilisez l'Editeur de requ\*^etes.
.NH 2 
Rechercher la s\*'election
.XS
recherche rapide
.XE
.XS
s\*'election
.XE
.XS
S\*'election, rechercher
.XE
.PP
 Pour proc\*'eder \*`a une recherche rapide en utilisant le texte
en surbrillance:
.IP \(rh
 Affichez en surbrillance le texte qui fera l'objet de la recherche.
(Placez le pointeur au d\*'ebut du texte. Maintenez le bouton 1 de la
souris enfonc\*'e et faites glisser le rectangle de s\*'election jusqu'\*`a
la fin du texte.)
*
.FS
* 
 Le texte en surbrillance ne doit pas se trouver dans la fen\*^etre
de lecture. Il peut se trouver dans une fen\*^etre quelconque de votre
syst\*`eme.
.FE
 
.IP \(rh
 Choisissez S&eacute;lection sur le menu Rechercher de
la fen\*^etre de lecture.
 Le Gestionnaire des informations affiche le texte affich\*'e en
surbrillance dans le champ de recherche rapide et lance la recherche.
.NH 1 
D\*'efinir des recherches d\*'etaill\*'ees
.XS
rechercher
.XE
.XS
m\*'ethode d\*'etaill\*'ee
.XE
.PP
 Les recherches d\*'etaill\*'ees vous permettent de produire
des concordances plus pr\*'ecises dans vos r\*'esultats de recherche.
Pour d\*'efinir une requ\*^ete d\*'etaill\*'ee, utilisez l'Editeur
de requ\*^etes et proc\*'edez aux op\*'erations suivantes:
.IP -
 Entrer une requ\*^ete d\*'etaill\*'ee. Voir 
role="JumpText" Entrer une requ\*^ete de recherche d\*'etaill\*'ee.
.IP -
 Sp\*'ecifier le pr\*'efixe de requ\*^ete. Voir 
role="JumpText" Sp\*'ecifier le pr\*'efixe de la requ\*^ete.
.IP -
 D\*'efinir des relations dans la requ\*^ete. Voir 
role="JumpText" D\*'efinir des relations dans la requ\*^ete.
 Vous pouvez \*'egalement d\*'efinir l'\*'etendue de la recherche
\*`a partir de l'Editeur de requ\*^etes. Pour des informations compl\*'ementaires,
consultez la section D\*'efinir l'\*'etendue des recherches.
.NH 2 
Entrer une requ\*^ete de recherche d\*'etaill\*'ee
.XS
rechercher
.XE
.XS
entrer des requ\*^etes
.XE
.PP
 Pour entrer une requ\*^ete de recherche d\*'etaill\*'ee:
.IP \(rh
 Ouvrez l'Editeur de requ\*^etes en choisissant Editeur
de requ&ecirc;tes sur le menu Rechercher dans une fen\*^etre de lecture.
Le Gestionnaire des informations affiche la fen\*^etre Editeur de requ&ecirc;tes.
Fen\*^etre de l'Editeur de requ&ecirc;tes
.PSPIC "./graphics/qeditwin.eps"
.IP \(rh
 Cliquez sur le bouton Pr\*'efixe. L'Editeur de requ&ecirc;tes
affiche la liste des pr\*'efixes. Cliquez sur le pr\*'efixe \*`a
utiliser pour la requ\*^ete: Contient, Ne contient pas, Commence par,
ou Ne commence pas par.
.IP \(rh
 Tapez le premier terme de la recherche dans le champ de saisie
\*`a droite du bouton Pr\*'efixe.
.IP \(rh
 Pour inclure un autre terme dans la recherche, cliquez sur
le bouton de connexion \*`a droite du champ de saisie. L'Editeur de requ&ecirc;tes
affiche la liste des connexions. S\*'electionnez la connexion \*`a
utiliser pour la requ\*^ete: Ou ou Et. R\*'ep\*'etez les \*'etapes
2 \*`a 4 jusqu'\*`a la fin de la requ\*^ete.
.IP \(rh
 Appuyez sur la touche Retour ou cliquez sur le bouton Rechercher
pour lancer la recherche. Le Gestionnaire des informations affiche les valeurs
correspondantes identifi\*'ees dans la fen\*^etre R\*'esultats
de la recherche. La figure Fen\*^etre R\*'esultats de la recherche
repr\*'esente une fen\*^etre R\*'esultats de la recherche.
 A mesure que vous cr\*'eez votre requ\*^ete, l'Editeur de requ\*^etes
affiche la requ\*^ete telle qu'elle est d\*'efinie dans la zone d'affichage
Requ\*^ete au bas de la fen\*^etre. La d\*'efinition de la requ\*^ete
explique comment entrer la requ\*^ete \*`a partir d'un champ de recherche
rapide.
.NH 2 
Sp\*'ecifier le pr\*'efixe de la requ\*^ete
.XS
requ\*^ete
.XE
.XS
sp\*'ecifier le pr\*'efixe
.XE
.XS
pr\*'efixe
.XE
.XS
pour requ\*^etes
.XE
.PP
 Pour commencer la sp\*'ecification d'une requ\*^ete, utilisez
le bouton Pr\*'efixe pour indiquer si votre recherche \fI Contient\fR , \fI Ne contient pas\fR , \fI Commence par\fR  ou \fI Ne commence pas par\fR  le texte que vous
tapez dans le champ d'entr\*'ee de recherche. Pour ce faire:
.IP \(rh
 Cliquez sur le bouton Pr\*'efixe. L'Editeur de requ&ecirc;tes
affiche la liste des pr\*'efixes.
.IP \(rh
 Cliquez sur le pr\*'efixe \*`a utiliser pour votre
requ\*^ete:
.IP "Contient"
 Localise les sections contenant le texte \*`a rechercher.
.IP "Ne contient pas"
 Localise des sections ne contenant pas le texte \*`a rechercher.
.IP "Commence par"
 Localise les sections contenant des mots commen\*,cant par le texte
\*`a rechercher.
.IP "Ne commence pas par"
 Localise les sections ne contenant pas les mots commen\*,cant par
le texte \*`a rechercher.
 D\*`es que vous s\*'electionnez le pr\*'efixe, l'Editeur
de requ\*^etes l'affiche sur le bouton Pr\*'efixe. Entrez ensuite le
reste de votre requ\*^ete.
.NH 2 
D\*'efinir des relations dans la requ\*^ete
.XS
requ\*^ete
.XE
.XS
d\*'efinir des relations
.XE
.XS
relations
.XE
.XS
d\*'efinir,
dans une requ\*^ete
.XE
.PP
 L'Editeur de requ&ecirc;tes vous permet d'inclure plusieurs mots
ou phrases dans une recherche. Pour sp\*'ecifier une relation entre les
diverses parties d'une requ\*^ete, utilisez le bouton de connexion (\*`a
droite du champ de saisie) pour afficher la liste Connexions. A partir de
la liste Connexions, s\*'electionnez la relation d\*'esir\*'ee.
Vous pouvez sp\*'ecifier que la partie actuelle ET la partie suivante
de la requ\*^ete doivent se r\*'ev\*'eler vraies, ou qu'une seule
partie doit se produire. En d'autres termes, une relation d\*'efinit les
crit\*`eres d'obtention d'une concordance valide.
 Pour d\*'efinir une relation:
.IP \(rh
 Sp\*'ecifiez le pr\*'efixe et le texte de recherche
de la premi\*`ere partie de la requ\*^ete.
.IP \(rh
 Cliquez sur le bouton de connexion. L'Editeur de requ&ecirc;tes
affiche la liste Connexions.
.IP \(rh
 Cliquez sur l'op\*'erateur logique destin\*'e \*`a
la relation que vous souhaitez d\*'efinir:
.IP "Ou"
 Localise les sections contenant une cha\*^ine correspondant \*`a
la partie actuelle de la requ\*^ete OU \*`a la partie suivante de la
requ\*^ete, ou aux deux.
.IP "Et"
 Localise les sections contenant une cha\*^ine correspondant \*`a
la partie actuelle de la requ\*^ete ET \*`a la partie suivante de la
requ\*^ete.
 D\*`es que vous en s\*'electionnez une, l'Editeur de requ\*^etes
affiche la connexion choisie (l'op\*'erateur logique) sur le bouton de
connexion et entame la ligne suivante de la requ\*^ete.
.NH 1 
D\*'efinir l'\*'etendue des recherches
.XS
rechercher
.XE
.XS
d\*'efinir l'\*'etendue
.XE
.XS
\*'etendue
.XE
.XS
d\*'efinir
.XE
.PP
 Les \*'etendues vous permettent de limiter l'envergure de vos recheches.
Elle r\*'eduisent la taille des listes de r\*'esultats de recherche
en les limitant \*`a des concordances plus significatives. De mani\*`ere
plus pr\*'ecise, vous pouvez utiliser des \fB \*'etendues de
recherche\fR  pour limiter les livres et types de donn\*'ees (des
tables, par exemple) qui seront incluses dans une recherche.
 Le Gestionnaire des informations propose des \*'etendues permettant
de rechercher parmi la section en cours, toute la biblioth\*`eque d'informations
ou un rayon sp\*'ecifique. Ces \*'etendues de recherche pr\*'e-d\*'efinies
incluent tous les types de donn\*'ees, y compris les titres, le corps
du texte, les index, les tables et les graphiques. Vous pouvez d\*'efinir
des \*'etendues de recherche personnalis\*'ees afin de sp\*'ecifier
les livres et les types de donn\*'ees que vous incluez d'habitude dans
vos recherches.
 Le reste de cette section propose des informations sur:
.IP -
 S\*'electionner une \*'etendue de
.IP -
 Cr\*'eer des \*'etendues de recherche
.IP -
 Modifier les \*'etendues de recherche
.IP -
 Copier des \*'etendues de recherche
.IP -
 Supprimer des \*'etendues de recherche
.NH 2 
S\*'electionner une \*'etendue de
recherche
.XS
rechercher
.XE
.XS
s\*'electionner
des \*'etendues
.XE
.XS
\*'etendue
.XE
.XS
s\*'electionner
.XE
.PP
 Lorsque vous d\*'emarrez une recherche, le logiciel utilise par
d\*'efaut la derni\*`ere \*'etendue sp\*'ecifi\*'ee pour
cette zone de recherche. La fen\*^etre de lecture et l'Editeur de requ\*^etes
maintiennent leurs propres \*'etendues de recherche par d\*'efaut.
 Par exemple, lorsque vous lancez une recherche \*`a partir de la
fen\*^etre de lecture, le Gestionnaire des informations utilise la derni\*`ere
\*'etendue de la recherche utilis\*'ee. Si vous n'avez pas encore
effectu\*'e de recherche au cours de cette session d'exploration, le Gestionnaire
des informations utilise la section en cours comme \*'etendue des recherches
lanc\*'ees \*`a partir de la fen\*^etre de lecture. Il utilise
Toutes les biblioth\*`eques comme \*'etendue par d\*'efaut pour
les recherches \*'emanant de l'Editeur de requ\*^etes.
 Vous pouvez s\*'electionner une autre \*'etendue de recherche
\*`a l'aide du bouton Etendue de recherche au bas de la fen\*^etre
de lecture. Ou alors, utilisez le bouton Nom d'\*'etendue dans l'Editeur
de requ\*^etes.
.NH 3 
S\*'electionner une \*'etendue \*`a
partir de la fen\*^etre de lecture
.PP
 Utilisez le bouton Etendue de recherche pour identifier les livres \*`a
inclure dans les recherches d\*'emarr\*'ees \*`a partir du champ
de recherche rapide. Pour utiliser une \*'etendue de recherche autre que
celle qui est affich\*'ee:
.IP \(rh
 Cliquez sur le bouton Etendue de recherche \*`a gauche
du champ de recherche rapide. Le Gestionnaire des informations affiche la
liste des \*'etendues de recherche. Cette liste regroupe les \*'etendues
pr\*'e-d\*'efinies ainsi que toute \*'etendue cr\*'e\*'ee
et enregistr\*'ee \*`a l'aide de l'Editeur d'\*'etendues.
.IP \(rh
 S\*'electionnez l'\*'etendue de recherche \*`a
utiliser. Le Gestionnaire des informations remplace le nom d'\*'etendue
pr\*'ec\*'edent par le nouveau nom d'\*'etendue sur le bouton
Etendue de recherche. La nouvelle \*'etendue reste en vigueur pour le
reste de la session o\*`u jusqu'\*`a ce que vous la modifiiez.
.NH 3 
S\*'electionner une \*'etendue \*`a
partir de l'Editeur de requ\*^etes
.PP
 Vous pouvez utiliser le bouton Nom d'\*'etendue pour identifier
les livres auxquels \*'etendre les recherches lanc\*'ees \*`a
l'aide de l'Editeur de requ\*^etes. Pour utiliser une \*'etendue de
recherche diff\*'erente de l'\*'etendue sugg\*'er\*'ee:
.IP \(rh
 Cliquez sur le bouton Nom d'&eacute;tendue. Le syst\*`eme
affiche la liste des noms des \*'etendues de recherche disponibles. Cette
liste contient \*`a la fois les \*'etendues pr\*'e-d\*'efinies
et cr\*'e\*'ees par l'utilisateur.
.IP \(rh
 A partir de la liste des noms d'\*'etendue, s\*'electionnez
l'\*'etendue \*`a utiliser.
.NH 2 
Cr\*'eer des \*'etendues de recherche
.XS
rechercher
.XE
.XS
cr\*'eer des \*'etendues
.XE
.XS
\*'etendue
.XE
.XS
cr\*'eer
.XE
.PP
 Si vous explorez fr\*'equemment une partie de la biblioth\*`eque
d'informations \*`a la recherche d'informations sp\*'ecifiques, il
sera peut-\*^etre utile de cr\*'eer et d'enregistrer une \*'etendue
de recherche personnalis\*'ee. Cr\*'eez ou modifiez vos \*'etendues
de recherche \*`a l'aide de l'Editeur d'\*'etendues.
.XS
Editeur d'\*'etendues
.XE
.NH 3 
Ouvrir l'Editeur d'\*'etendues de recherche
.XS
rechercher
.XE
.XS
Editeur d'\*'etendues
.XE
.XS
Editeur d'\*'etendues
.XE
.XS
ouvrir
.XE
.XS
\*'etendue
.XE
.XS
ouvrir l'Editeur
.XE
.PP
 Pour ouvrir l'Editeur d'\*'etendues \*`a partir de l'Editeur
de requ\*^etes, cliquez sur le bouton Editeur d'\*'etendues au bas
de la fen\*^etre Editeur de requ&ecirc;tes.
 Pour ouvrir l'Editeur d'\*'etendues \*`a partir de la fen\*^etre
de lecture, cliquez sur le bouton Editeur d'\*'etendues dans le coin inf\*'erieur
droit de la fen\*^etre ou choisissez Editeur d'\*'etendues sur le menu
Rechercher.
 Le Gestionnaire des informations affiche l'Editeur d'\*'etendues,
comme le montre la figure suivante.
Fen\*^etre de l'Editeur d'\*'etendues
.PSPIC "./graphics/scopedit.eps"
.NH 3 
Cr\*'eer une nouvelle \*'etendue
de recherche
.XS
Editeur d'\*'etendues
.XE
.XS
cr\*'eer une \*'etendue
.XE
.XS
\*'etendue
.XE
.XS
cr\*'eer
.XE
.PP
 Le c\*^ot\*'e gauche de la fen\*^etre de l'Editeur d'\*'etendues
contient la liste des livres de la biblioth\*`eque d'informations. Pour
\*'etendre ou r\*'eduire cette liste, cliquez sur la fl\*`eche
vers la droite ou vers la gauche qui pr\*'ec\*`ede chaque titre de
livre.
 Le c\*^ot\*'e droit de la fen\*^etre de l'Editeur d'\*'etendues
contient la liste des composants de livre que vous pouvez inclure dans l'\*'etendue.
Par d\*'efaut, le Gestionnaire des informations \*'etend votre recherche
\*`a tous les composants.
 Pour cr\*'eer une nouvelle \*'etendue de recherche:
.IP \(rh
 Cliquez sur le bouton Nouveau.
.IP \(rh
 Cliquez sur les noms des livres et composants \*`a inclure
dans l'\*'etendue.
.IP \(rh
 Cliquez sur le bouton Enregistrer. Le Gestionnaire des informations
ouvre la fen\*^etre Enregistrer l'\*'etendue repr\*'esent\*'ee
par la figure suivante.
Fen\*^etre Enregistrer l'\*'etendue
.PSPIC "./graphics/savescop.eps"
.IP \(rh
 Tapez le nom de la nouvelle \*'etendue dans le champ de
saisie et cliquez sur OK. Le Gestionnaire des informations affiche le nom
de la nouvelle \*'etendue dans la fen\*^etre de l'Editeur d'&eacute;tendues.
 Pour utiliser la nouvelle \*'etendue dans une requ\*^ete, acc\*'edez-y
comme \*`a toute autre \*'etendue pr\*'e-d\*'efinie.
.NH 3 
Modifier les \*'etendues de recherche
.XS
Editeur d'\*'etendues
.XE
.XS
modifier l'\*'etendue
.XE
.XS
\*'etendue
.XE
.XS
modifier
.XE
.PP
 Pour modifier une \*'etendue existante:
.IP \(rh
 Cliquez sur le bouton Nom d'&eacute;tendue dans la fen\*^etre
de l'Editeur d'&eacute;tendues. Le Gestionnaire des informations affiche
la liste des \*'etendues.
.IP \(rh
 S\*'electionnez l'\*'etendue \*`a modifier. Le
nom de l'\*'etendue s\*'electionn\*'ee appara\*^it sur le bouton
Nom d'&eacute;tendue.
.IP \(rh
 Pour remplacer les livres compris dans l'\*'etendue, affichez
en surbrillance les titres des livres \*`a s\*'electionner.
.IP \(rh
 Pour modifier la liste des composants inclus dans l'\*'etendue,
affichez en surbrillance les noms des composants.
.IP \(rh
 Cliquez sur le bouton Enregistrer pour sauvegarder ces modifications.
.IP \(rh
 Apr\*`es avoir apport\*'e toutes les modifications
n\*'ecessaires, cliquez sur le bouton Fermer.
*
.FS
* 
 Pour r\*'etablir la d\*'efinition initiale de l'\*'etendue,
cliquez sur le bouton Restaurer au bas de la fen\*^etre.
.FE
 
 Le Gestionnaire des informations m\*'emorise en tant qu'\*'etendue
en cours celle que vous utilisez pr\*'ealablement pour vos recherches.
Si vous avez apport\*'e des modifications \*`a l'\*'etendue en
cours, le Gestionnaire des informations applique ces modifications \*`a
la prochaine recherche effectu sur cette \*'etendue.
.NH 3 
Copier des \*'etendues de recherche
.XS
Editeur d'\*'etendues
.XE
.XS
copier une \*'etendue
.XE
.XS
\*'etendue
.XE
.XS
copier
.XE
.PP
 Pour copier une \*'etendue de recherche:
.IP \(rh
 Cliquez sur le bouton Nom d'&eacute;tendue dans la fen\*^etre
de l'Editeur d'&eacute;tendues. Le Gestionnaire des informations affiche
la liste des \*'etendues.
.IP \(rh
 S\*'electionnez l'\*'etendue \*`a copier. Le nom
de l'\*'etendue s\*'electionn\*'ee appara\*^it sur le bouton
Nom d'&eacute;tendue.
.IP \(rh
 Cliquez sur le bouton Copier au bas de la fen\*^etre. Le
Gestionnaire des informations affiche la fen\*^etre Enregistrer l'\*'etendue.
.IP \(rh
 Tapez le nom de la copie et cliquez sur OK pour l'enregistrer.
 Notez que l'\*'etendue existe toujours sous son nom initial. La
section Supprimer des \*'etendues de recherche explique comment
supprimer les \*'etendues superflues.
.NH 3 
Supprimer des \*'etendues de recherche
.XS
Editeur d'\*'etendues
.XE
.XS
supprimer une \*'etendue
.XE
.XS
\*'etendue
.XE
.XS
supprimer
.XE
.PP
 Pour supprimer une \*'etendue de recherche pr\*'ealablement
enregistr\*'ee:
.IP \(rh
 Cliquez sur le bouton Nom d'&eacute;tendue dans la fen\*^etre
de l'Editeur d'&eacute;tendues. Le Gestionnaire des informations affiche
la liste des \*'etendues.
.IP \(rh
 S\*'electionnez l'\*'etendue \*`a supprimer. Le
nom de l'\*'etendue s\*'electionn\*'ee appara\*^it sur le bouton
Nom d'&eacute;tendue.
.IP \(rh
 Cliquez sur le bouton Supprimer au bas de la fen\*^etre.
Le Gestionnaire des informations supprime l'\*'etendue et affiche l'\*'etendue
suivante dans la liste des \*'etendues.
.NH 1 
Consulter les r\*'esultats de la recherche
.XS
rechercher
.XE
.XS
consulter les r\*'esultats
.XE
.XS
r\*'esultats de la recherche
.XE
.PP
 Lorsque vous effectuez une recherche, le Gestionnaire des informations
affiche la liste des sections contenant des valeurs correspondant \*`a
la recherche. Cette liste appara\*^it dans la fen\*^etre R\*'esultats
de la recherche. A partir de cette fen\*^etre, passez \*`a une des
sections list\*'ees en cliquant simplement sur son titre.
 La figure suivante illustre le mode d'affichage des concordances par
ordre d\*'ecroissant d'importance. L'ic\*^one \*`a gauche du titre
du livre indique la fr\*'equence d'apparition du terme recherch\*'e
dans la section donn\*'ee.
Fen\*^etre R\*'esultats de la recherche
.PSPIC "./graphics/serchres.eps"
 Si la liste R\*'esultats de la recherche vous semble incompl\*`ete,
trop longue ou erron\*'ee, v\*'erifiez que vous utilisez bien l'\*'etendue
de recherche appropri\*'ee. V\*'erifiez \*'egalement votre r\*'eglage
de pr\*'ef\*'erence concernant le maximum de correspondances.
 Lors de l'ex\*'ecution de recherches multiples, nous vous conseillons
d'ancrer la premi\*`ere fen\*^etre R\*'esultats de la recherche.
De cette mani\*`ere, lorsque vous proc\*'edez \*`a une autre recherche,
les nouveaux r\*'esultats ne remplaceront pas ceux de la premi\*`ere
recherche. Au contraire, ils seront affich\*'es dans une fen\*^etre
distincte de R\*'esultats de la recherche.
.NH 2 
Parcourir les correspondances de la recherche
.XS
rechercher
.XE
.XS
parcourir les correspondances
.XE
.XS
R\*'esultats de la recherche
.XE
.XS
parcourir les correspondances
.XE
.XS
r\*'eponses pertinentes
.XE
.PP
 Apr\*`es vous \*^etre rendu \*`a une section \*`a partir
de votre liste R\*'esultats de la recherche, il sera peut-\*^etre n\*'ecessaire
de consulter chaque correspondance (ou \fI r\*'eponse pertinente\fR ) figurant dans la section. Les correspondances sont affich\*'ees
en gras, soulign\*'ees et dans une couleur diff\*'erente. La correspondance
sur laquelle vous vous trouvez actuellement est \*'egalement encadr\*'ee
d'un rectangle de pointill\*'es.
 Pour parcourir les r\*'eponses pertinente<?Pub Caret> au sein d'une
section, utilisez les boutons Recherche suivante et Recherche pr\*'ec\*'edente
de la barre d'outils de la fen\*^etre de lecture. (Vous pouvez aussi choisir
Recherche suivante et Recherche pr\*'ec\*'edente sur le menu Aller.)
.PSPIC "./graphics/serchbut.eps"
 Recherche suivante affiche la correspondance ou \fI r\*'eponse
pertinente\fR  suivante. Recherche pr\*'ec\*'edente affiche
la correspondance pr\*'ec\*'edente.
 Si vous vous trouvez sur la derni\*`ere correspondance de la section,
le bouton Recherche suivante est estomp\*'e (affich\*'e en gris).
Si vous trouvez sur la premi\*`ere correspondance de la section, le bouton
Recherche pr\*'ec\*'edente est estomp\*'e.
.NH 2 
Revoir les r\*'esultats d'une recherche
pr\*'ec\*'edente
.XS
rechercher
.XE
.XS
revoir les r\*'esultats pr\*'ec\*'edents
.XE
.XS
R\*'esultats de la recherche
.XE
.XS
revoir les pr\*'ec\*'edents
.XE
.PP
 Si vous omettez d'ancrer les r\*'esultats d'une recherche pr\*'ec\*'edente,
il est toujours possible de r\*'ecup\*'erer cette liste. Pour revoir
une liste R\*'esultats de la recherche ant\*'erieure:
.IP \(rh
 Choisissez Historique de la recherche sur le menu Rechercher
d'une fen\*^etre de lecture quelconque.
 Le Gestionnaire des informations affiche la fen\*^etre Historique
de la recherche.
Fen\*^etre Historique de la recherche
.PSPIC "./graphics/shistwin.eps"
.IP \(rh
 Cliquez deux fois sur la recherche dont vous souhaitez consulter
les r\*'esultats.
 Le Gestionnaire des informations affiche la fen\*^etre R\*'esultats
de la recherche de la recherche s\*'electionn\*'ee.
 Vous ne pouvez r\*'ecup\*'erer de la sorte que les r\*'esultats
des recherches effectu\*'ees au cours de la session d'exploration en cours.
.bp
<?Pub *0000036750>
\" <!-- $XConsortium: ch05.sgm /main/2 1996/12/17 15:36:32 rws $ -->
\" <!-- (c) Copyright 1996 Digital Equipment Corporation. -->
\" <!-- (c) Copyright 1996 Hewlett-Packard Company. -->
\" <!-- (c) Copyright 1996 International Business Machines Corp. -->
\" <!-- (c) Copyright 1996 Sun Microsystems, Inc. -->
\" <!-- (c) Copyright 1996 Novell, Inc. -->
\" <!-- (c) Copyright 1996 FUJITSU LIMITED. -->
\" <!-- (c) Copyright 1996 Hitachi. -->
.TL
 Utiliser des signets et des notes
.XS
signets
.XE
.XS
utiliser
.XE
.LP
 Il vous sera probablement utile d'identifier des sections sp\*'ecifiques
ou d'ajouter des commentaires \*`a un passage, comme vous le feriez dans
un livre imprim\*'e traditionnel. Pour personnaliser les livres en ligne
de cette mani\*`ere, vous pouvez cr\*'eer des \fB signets\fR 
et ins\*'erer des \fB notes\fR  \*`a c\*^ot\*'e
de passages de texte ou d'\*'el\*'ements graphiques.
 Un \fI signet\fR  consiste donc essentiellement en une
marque d'emplacement. Une \fI note\fR  est un signet annot\*'e.
L'Explorateur repr\*'esente les signets et les notes par des ic\*^ones
dans la marge gauche de la fen\*^etre de lecture.
 La figure suivante repr\*'esente un signet.
Un signet vierge
.PSPIC "./graphics/bkmark.eps"
 La figure suivante repr\*'esente une note.
Un signet avec note
.PSPIC "./graphics/bknote.eps"
 Une ligne peut contenir plusieurs signets. La figure suivante repr\*'esente
des signets multiples.
Signets multiples
.PSPIC "./graphics/bkmarks.eps"
 Les signets et notes que vous cr\*'eez dans le Gestionnaire des
informations sont priv\*'es. Les autres utilisateurs ne peuvent y acc\*'eder.
Pour cr\*'eer des signets et des notes, urilisez le menu Rep\*`eres
de la fen\*^etre de lecture.
.NH 1 
Cr\*'eer des signets
.XS
signets
.XE
.XS
cr\*'eer
.XE
.PP
 Vous pouvez cr\*'eer un signet vierge pour indiquer votre position,
ou cr\*'eer un signet accompagn\*'e de notes.
*
.FS
* 
 Il est toujours possible d'\*'editer un signet vierge existant pour
lui ajouter des notes.
.FE
 
.NH 2 
Cr\*'eer un signet vierge
.XS
signets
.XE
.XS
vierge, cr\*'eer
.XE
.XS
signet vierge
.XE
.XS
cr\*'eer
.XE
.PP
 Pour cr\*'eer un signet vierge:
.IP \(rh
 Affichez en surbrillance le texte ou l'\*'el\*'ement
graphique \*`a rep\*'erer. (Placez le pointeur au d\*'ebut du
texte. Maintenez le bouton gauche de la souris enfonc\*'e et faites glisser
le pointeur jusqu'\*`a la fin du texte.)
.IP \(rh
 Choisissez Cr\*'eer un signet sur le menu Rep\*`eres.
 Le Gestionnaire des informations affiche l'ic\*^one signet dans la
marge gauche de la ligne contenant le texte en surbrillance. Par d\*'efaut,
le texte s\*'electionn\*'e est utilis\*'e comme nom du signet.
Pour obtenir des informations sur la modification des noms de signet, consultez
la sectionEditer les signets.
.NH 2 
Cr\*'eer un signet avec notes
.XS
signets
.XE
.XS
avec notes, cr\*'eer
.XE
.PP
 Pour cr\*'eer un signet avec notes:
.IP \(rh
 Affichez en surbrillance le texte ou l'\*'el\*'ement
graphique \*`a rep\*'erer.
.IP \(rh
 Choisissez Cr\*'eer une note sur le menu Rep\*`eres.
 Le Gestionnaire des informations affiche l'Editeur de signets.
.IP \(rh
 Tapez votre texte dans le champ Notes.
.IP \(rh
 Cliquez sur OK pour enregistrer la note et refermer l'Editeur
de signets.
 Vous pouvez aussi ajouter des notes \*`a un signet vierge existant.
La sectionEditer les signets offre un compl\*'ement
d'information \*`a ce sujet.
.NH 1 
Lister les signets
.XS
signets
.XE
.XS
lister
.XE
.PP
 Pour afficher la liste de tous vos signets, choisissez Lister les signets
sur le menu Rep\*`eres d'une fen\*^etre de lecture quelconque. Le Gestionnaire
des informations affiche la fen\*^etre Liste des signets de l'utilisateur
qui regroupe \*`a la fois les signets vierges et annot\*'es.
 Pour afficher la section dans laquelle appara\*^it un signet, cliquez
deux fois sur le nom du signet.
.NH 1 
Afficher les signets et notes
.XS
signets
.XE
.XS
afficher
.XE
.PP
 Pour afficher un signet existant et les notes qui l'accompagnent, cliquez
deux fois sur l'ic\*^one du signet dans la fen\*^etre de lecture. Le
Gestionnaire des informations ouvre la fen\*^etre de l'Editeur de signets,
repr\*'esent\*'ee par la f<?Pub Caret>igure suivante. L'Editeur de
signets permet de modifier le nom et les notes du signet.
Editeur de signets
.PSPIC "./graphics/bkmkedit.eps"
 Si plusieurs signets figurent sur une ligne, le Gestionnaire des informations
les repr\*'esente par une ic\*^one qui a l'aspect de multiples signets.
Pour consulter la liste des signets d'une ligne, cliquez deux fois sur l'ic\*^one
signets multiples. S\*'electionnez ensuite le signet \*`a afficher
\*`a partir de la liste Editer le signet.
.NH 1 
Editer les signets
.XS
signets
.XE
.XS
\*'editer
.XE
.PP
 Vous souhaitez peut-\*^etre ajouter des commentaires \*`a un
signet vierge existant ou modifier des commentaires apport\*'es lors d'une
session d'exploration ant\*'erieure.
 Pour \*'editer ou ajouter des notes \*`a un signet:
.IP \(rh
 Cliquez sur l'ic\*^one du signet \*`a \*'editer.
.IP \(rh
 Choisissez Modifier la s\*'election sur le menu Rep\*`eres.
 Le Gestionnaire des informations ouvre l'Editeur de signets qui affiche
le nom actuel du signet ainsi que toute note lui \*'etant associ\*'ee,
le cas \*'ech\*'eant.
.IP \(rh
 Apportez vos modifications au nom ou aux notes du signet.
.IP \(rh
 Cela \*'etant fait, cliquez sur OK.
.B1
 Une m\*'ethode plus rapide consiste \*`a ouvrir l'Editeur de
signets en cliquant deux fois sur l'ic\*^one du signet.
.B2
.NH 1 
D\*'eplacer les signets
.XS
signets
.XE
.XS
d\*'eplacer
.XE
.PP
 Vous pouvez d\*'eplacer un signet de son emplacement actuel vers
un autre endroit de la m\*^eme fen\*^etre de lecture. Pour d\*'eplacer
un signet:
.IP \(rh
 Cliquez sur l'ic\*^one du signet \*`a d\*'eplacer.
.IP \(rh
 Affichez en surbrillance du texte sur la ligne vers laquelle
vous souhaitez d\*'eplacer le signet.
.IP \(rh
 Choisissez D\*'eplacer la s\*'election sur le menu
Rep\*`eres.
.NH 1 
Supprimer signets et notes
.XS
signets
.XE
.XS
supprimer
.XE
.PP
 Vous avez la possibilit\*'e de supprimer tout signet devenu superflu.
Pour supprimer un signet:
.IP \(rh
 Cliquez sur l'ic\*^one du signet \*`a supprimer.
.IP \(rh
 Choisissez Supprimer la s\*'election sur le menu Rep\*`eres.
 Le Gestionnaire des informations supprime le signet s\*'electionn\*'e
de la marge du livre.
.bp
<?Pub *0000012681>
\" <!-- $XConsortium: ch06.sgm /main/2 1996/12/17 15:36:41 rws $ -->
\" <!-- (c) Copyright 1996 Digital Equipment Corporation. -->
\" <!-- (c) Copyright 1996 Hewlett-Packard Company. -->
\" <!-- (c) Copyright 1996 International Business Machines Corp. -->
\" <!-- (c) Copyright 1996 Sun Microsystems, Inc. -->
\" <!-- (c) Copyright 1996 Novell, Inc. -->
\" <!-- (c) Copyright 1996 FUJITSU LIMITED. -->
\" <!-- (c) Copyright 1996 Hitachi. -->
.TL
 G\*'erer les graphiques
.XS
graphiques
.XE
.XS
g\*'erer
.XE
.XS
graphiques
.XE
.LP
 Il se r\*'ev\*`elera peut-\*^etre n\*'ecessaire de supprimer
un graphique du document, de le placer dans une fen\*^etre distincte afin
de le consulter ou de le manipuler (par exemple, le redimensionner). On dit
d'un tel (\*'el\*'ement) graphique qu'il est "d\*'etach\*'e".
Vous risquez de devoir d\*'etacher un graphique dans les circonstances
suivantes:
.IP -
 Le fait de maintenir l'affichage d'un graphique vous permet
de le consulter alors que vous poursuivez votre lecture.
.IP -
 Le d\*'etachement du graphique vous permet de comparer
des images \*`a la m\*^eme section ou \*`a des sections diff\*'erentes.
.IP -
 En d\*'etachant un graphique de tr\*`es grande taille
ou qui d\*'eborde simplement de la largeur par d\*'efaut de votre
fen\*^etre de lecture, il est possible de redimensionner l'image graphique
sans redimensionner la fen\*^etre de lecture.
.IP -
 L'insertion de certains graphiques risquant de bouleverser
consid\*'erablement la disposition du texte, vous avez la possibilit\*'e
d'am\*'eliorer la lisibilit\*'e d'une section en en d\*'etachant
les graphiques.
 Il est tr\*`es facile de manipuler et de g\*'erer les graphiques
d\*'etach\*'es. Plus pr\*'ecis\*'ement, il est possible de
:
.IP -
 Redimensionner la fen\*^etre du graphique et positionner
le bouton panoramique. Voir Redimensionner la fen\*^etre graphique.
.IP -
 Redimensionner les graphiques. Voir 
Redimensionner les graphiques.
.IP -
 Localiser la section initiale d'un graphique. Voir 
Localiser la section d'origine d'un graphique.
.IP -
 Rattacher des graphiques. Voir Rattacher les graphiques.
.NH 1 
D\*'etacher les graphiques
.XS
graphiques
.XE
.XS
d\*'etacher
.XE
.PP
 Pour d\*'etacher un graphique d'un livre:
.IP \(rh
 Choisissez D\*'etacher le graphique sur le menu Options.
Le Gestionnaire des informations affiche un curseur en forme de viseur.
.IP \(rh
 A l'aide du pointeur de la souris, cliquez sur le graphique
\*`a d\*'etacher. (Pour annuler l'op\*'eration, cliquez \*`a
un endroit quelconque en dehors du graphique.)
 Vous pouvez \*'egalement d\*'etacher un graphique en pla\*,cant
le pointeur sur le graphique et en cliquant sur le bouton droit de la souris.
Sur le menu dynamique affich\*'e, choisissez D\*'etacher le graphique.
 Si un graphique est s\*'electionn\*'e, le Gestionnaire des informations
l'affiche dans une fen\*^etre distincte. Dans la fen\*^etre de lecture,
une ic\*^one Graphique d\*'etach\*'e appara\*^it \*`a la
place du graphique.
.PSPIC "./graphics/dgrafico.eps"
 La figure suivante repr\*'esente un exemple de fen\*^etre Graphique
d\*'etach\*'e.
Fen\*^etre Graphique d\*'etach\*'e
.PSPIC "./graphics/graphwin.eps"
 Un graphique d\*'etach\*'e demeure dans sa fen\*^etre distincte
jusqu'\*`a ce que vous le rattachiez, refermiez la fen\*^etre Graphique
d\*'etach\*'e, ou terminiez la session d'exploration. Ceci signifie
qu'au cours d'une session, vous pouvez refermer la section dans laquelle appara\*^it
le graphique tout en affichant toujours ce dernier dans une fen\*^etre
s\*'epar\*'ee.
.NH 1 
Redimensionner la fen\*^etre graphique
.XS
graphiques
.XE
.XS
redimensionner la fen\*^etre
.XE
.PP
 Pour modifier la taille d'une fen\*^etre de graphique d\*'etach\*'e,
utilisez la souris pour faire glisser et d\*'eplacer les bords de la fen\*^etre,
ou utilisez le bouton Agrandir dans le coin sup\*'erieur droit du cadre
de la fen\*^etre.
 Lorsque vous r\*'eduisez la taille d'une fen\*^etre de graphique
d\*'etach\*'e, le Gestionnaire des informations affiche une case panoramique
dans un coin de la fen\*^etre. Pour afficher les parties masqu\*'ees
du graphique apr\*`es r\*'eduction de la taille de la fen\*^etre,
d\*'eplacez la case panoramique de mani\*`ere \*`a r\*'ev\*'eler
les sections \*`a consulter. La figure suivante repr\*'esente une
fen\*^etre de graphique d\*'etach\*'e avec une case panoramique
dans le coin sup\*'erieur gauche de la fen\*^etre.
.XS
case panoramique
.XE
.XS
avec fen\*^etre de graphique d\*'etach\*'e
.XE
Case panoramique
.PSPIC "./graphics/graphpan.eps"
 Pour d\*'eplacer la case panoramique dans un autre coin de la fen\*^etre
ou la supprimer compl\*`etement, s\*'electionnez l'emplacement que
vous pr\*'ef\*'erez sur le menu Case panoramique. Le Gestionnaire
des informations resitue la case panoramique dans le coin sp\*'ecifi\*'e
ou la supprime compl\*`etement.
.NH 1 
Redimensionner les graphiques
.XS
graphiques
.XE
.XS
redimensionner
.XE
.PP
 Utilisez les options du menu Visualiser pour sp\*'ecifier le mode
d'affichage d'un graphique redimensionnable dans la fen\*^etre Graphique
d\*'etach\*'e. Ces options sont d\*'esactiv\*'ees pour les
graphiques de dimensions fixes:
.IP "Adapter \*`a la fen\*^etre"
 Dimensionne le graphique de mani\*`ere \*`a le faire tenir dans
les limites de la fen\*^etre Graphique d&eacute;tach&eacute;.
.IP "Adapter au graphique"
 Redimensionne la fen\*^etre Graphique d&eacute;tach&eacute;
de mani\*`ere \*`a l'ajuster aux dimensions actuelles du graphique.
.IP "Pourcentages de dimensionnement"
 Augmentent ou r\*'eduisent la taille du graphique par rapport \*`a
ses dimensions initiales.
.IP "Personnaliser"
 Sp\*'ecifiez un pourcentage de dimensionnement pour le graphique
en cours.
.NH 1 
Localiser la section d'origine d'un graphique
.XS
graphique
.XE
.XS
localiser la section d'origine
.XE
.PP
 A partir d'une fen\*^etre Graphique d\*'etach\*'e, vous pouvez
ouvrir la section de laquelle le graphique a \*'et\*'e d\*'etach\*'e.
Pour ce faire, choisissez Afficher la section sur le menu Fichier de la fen\*^etre
Graphique d&eacute;tach&eacute;. Le Gestionnaire des informations
ouvre la fen\*^etre initiale dont vous avez d\*'etach\*'e le graphique<?Pub Caret> et
l'affiche \*`a l'avant-plan de vos autres fen\*^etres.
.NH 1 
Rattacher les graphiques
.XS
graphiques
.XE
.XS
rattacher
.XE
.PP
 Pour r\*'eins\*'erer un graphique dans le livre duquel vous
l'avez d\*'etach\*'e, utilisez une des m\*'ethodes suivantes:
.IP -
 Choisissez Attacher sur le menu Fichier de la fen\*^etre
Graphique d&eacute;tach&eacute;.
.IP -
 Choisissez Fermer sur le menu Fichier de la fen\*^etre
Graphique d&eacute;tach&eacute;.
.IP -
 Cliquez deux fois sur le bouton du menu Fen\*^etre (coin
sup\*'erieur gauche de la fen\*^etre Graphique d&eacute;tach&eacute;).
.IP -
 Placez le pointeur sur le graphique et cliquez sur le bouton
droit de la souris. Sur le menu dynamique affich\*'e, choisissez Attacher
le graphique.
 Le Gestionnaire des informations referme la fen\*^etre Graphique
d&eacute;tach&eacute; et r\*'eins\*`ere le graphique dans
le livre, que ce dernier soit ouvert ou pas.
.bp
<?Pub *0000013299>
\" <!-- $XConsortium: ch07.sgm /main/2 1996/12/17 15:36:49 rws $ -->
\" <!-- (c) Copyright 1996 Digital Equipment Corporation. -->
\" <!-- (c) Copyright 1996 Hewlett-Packard Company. -->
\" <!-- (c) Copyright 1996 International Business Machines Corp. -->
\" <!-- (c) Copyright 1996 Sun Microsystems, Inc. -->
\" <!-- (c) Copyright 1996 Novell, Inc. -->
\" <!-- (c) Copyright 1996 FUJITSU LIMITED. -->
\" <!-- (c) Copyright 1996 Hitachi. -->
.TL
 Imprimer
.XS
imprimer
.XE
.LP
 Le Gestionnaire des informations permet tout aussi bien d'imprimer certaines
parties d'un livre que tout un rayon de biblioth\*`eque. Il est tr\*`es
facile de sp\*'ecifier l'imprimante ou le fichier vers laquelle ou lequel
diriger l'impression.
*
.FS
* 
 Vous ne pouvez imprimer que les documents auxquels vous \*^etes autoris\*'e
(par licence) d'acc\*'eder.
.FE
 
 Pour lancer rapidement une impression (sans utiliser la bo\*^ite
de dialogue Imprimer), cliquez sur le bouton Imprimer de la fen\*^etre
Liste de livres ou de la fen\*^etre de lecture. Vous pouvez \*'egalement
choisir Imprimer sur le menu Fichier de la fen\*^etre Liste de livres ou
le menu Explorateur d'une fen\*^etre de lecture.
 Pour imprimer \*`a l'aide de la bo\*^ite de dialogue Imprimer,
choisissez Imprimer... sur le menu Fichier de la fen\*^etre Liste des livres
ou le menu Explorateur d'une fen\*^etre de lecture. Lorsque vous proc\*'edez
\*`a cette op\*'eration, le Gestionnaire des informations affiche
la bo\*^ite de dialogue Imprimer, comme l'indique la figure suivante.
Imprimer, bo\*^ite de dialogue
.PSPIC "./graphics/printwin.eps"
 La bo\*^ite de dialogue Imprimer contient les boutons suivants:
.IP "Imprimer"
 Transmet la ou les sections sp\*'ecifi\*'ee \*`a l'imprimante
ou au fichier d\*'esign\*'e.
.IP "Configuration..."
 Affiche la fen\*^etre Configuration de l'impression, \*`a partir
de laquelle vous configurerez des options sp\*'ecifiques \*`a une
imprimante et d\*'efinirez les options Imprimante et <comment>Traduire...
\*Q T\*^ache\*U  ou \*Q Travail\*U ????</comment>Job.
.IP "Annuler"
 Annule l'op\*'eration d'impression et referme la bo\*^ite de
dialogue Imprimer.
.IP "Aide"
 Affiche des informations relatives \*`a la bo\*^ite de dialogue
Imprimer.
 Pour un compl\*'ement d'information sur l'impression \*`a partir
du Gestionnaire des informations, voir:
.IP -
 Imprimer une section individuelle
.IP -
 Imprimer plusieurs sections
.IP -
 Sp\*'ecifier la ou les sections \*`a
.IP -
 Sp\*'ecifier la destination de l'impression
.NH 1 
Imprimer une section individuelle
.XS
imprimer
.XE
.XS
sections individuelles
.XE
.PP
 Pour imprimer rapidement la section que vous lisez actuellement, cliquez
sur le bouton Imprimer ou choisissez Imprimer sur le menu Explorateur. Le
Gestionnaire des informations imprime la section d\*'esir\*'ee sans
afficher la bo\*^ite de dialogue Imprimer.
 Pour imprimer la section actuelle \*`a l'aide de la bo\*^ite
de dialogue Imprimer:
.IP \(rh
 Choisissez Imprimer... sur le menu Explorateur. Le Gestionnaire
des informations affiche la bo\*^ite de dialogue Imprimer, la section que
vous lisez actuellement \*'etant s\*'electionn\*'ee.
.IP \(rh
 Dans la zone A imprimer, assurez-vous que le bouton de radio
Sections est s\*'electionn\*'e.
.IP \(rh
 Pour imprimer la section vers un fichier, cliquez sur le bouton
de radio Imprimer dans le fichier. Sp\*'ecifiez le chemin d'acc\*`es
du fichier dans la zone de saisie ou cliquez sur le bouton S\*'electionner
le fichier... pour parcourir \*`a la recherche du chemin d'acc\*`es
et du nom de fichier.
 Pour imprimer directement la section sur une imprimante, v\*'erifiez
que le bouton de radio Imprimer sur l'imprimante est s\*'electionn\*'e.
 Pour obtenir un compl\*'ement d'information, voir 
Sp\*'ecifier la destination de l'impression.
.IP \(rh
 Cliquez sur Imprimer pour imprimer la section s\*'electionn\*'ee.
.NH 1 
Imprimer plusieurs sections
.XS
imprimer
.XE
.XS
plusieurs sections
.XE
.PP
 Vous pouvez imprimer des sections multiples \*`a partir de la fen\*^etre
de lecture ou de la fen\*^etre Liste des livres.
.NH 2 
Depuis la fen\*^etre de lecture
.XS
imprimer
.XE
.XS
depuis la fen\*^etre de lecture
.XE
.PP
 Pour imprimer \*`a partir de la fen\*^etre de lecture:
.IP \(rh
 Choisissez Imprimer... sur le menu Explorateur. Le Gestionnaire
des informations affiche la bo\*^ite de dialogue Imprimer.
.IP \(rh
 Dans la zone A imprimer de la bo\*^ite de dialogue Imprimer,
cliquez sur le bouton de radio Hi\*'erarchie. Ce bouton indique au Gestionnaire
des informations d'imprimer la section actuelle et toutes ses sections subalternes.
 Pour obtenir un compl\*'ement d'information, voir 
Sp\*'ecifier la ou les sections \*`a.
.IP \(rh
 Pour imprimer les sections dans un fichier, cliquez sur le
bouton de radio Imprimer dans le fichier. Tapez le chemin d'acc\*`es du
fichier dans la zone de saisie ou cliquez sur le bouton S\*'electionner
le fichier pour parcourir \*`a la recherche du chemin d'acc\*`es et
du nom de fichier.
 Pour imprimer les sections directement sur une imprimante, cliquez sur
le bouton de radio Imprimer sur l'imprimante.
 Pour obtenir un compl\*'ement d'information, voir 
Sp\*'ecifier la destination de l'impression.
.IP \(rh
 Cliquez sur Imprimer pour imprimer les sections s\*'electionn\*'ees.
.NH 2 
Depuis la fen\*^etre Liste des livres
.XS
imprimer
.XE
.XS
depuis la fen\*^etre Liste de livres
.XE
.PP
 Pour imprimer \*`a partir de la fen\*^etre Liste de livres:
.IP \(rh
 Dans la fen\*^etre Liste de livres, maintenez la touche
Contr\*^ole enfonc\*'ee et cliquez sur les noms des sections \*`a
imprimer.
 Pour s\*'electionner un ensemble de sections contigu\:es, maintenez
la touche Maj enfonc\*'ee tout en faisant glisser le pointeur sur les
noms de section.
 Pour d\*'es\*'electionner une section, maintenez la touche Contr\*^ole
enfonc\*'ee et cliquez sur le nom de la section.
.IP \(rh
 Choisissez Imprimer... sur le menu Fichier. Le Gestionnaire
des informations affiche la bo\*^ite de dialogue Imprimer.
.IP \(rh
 Dans la zone A imprimer de la bo\*^ite de dialogue Imprimer,
cliquez sur le bouton de radio Sections.
*
.FS
* 
 Vous ne pouvez cliquer sur le bouton de radio Hi\*'erarchie si plusieurs
sections sont s\*'electionn\*'ees dans la Liste des livres.
.FE
 
 Pour obtenir un compl\*'ement d'information, voir 
Sp\*'ecifier la ou les sections \*`a.
.IP \(rh
 Pour imprimer les sections dans un fichier, cliquez sur le
bouton de radio Imprimer dans le fichier. Tapez le chemin d'acc\*`es du
fichier dans la zone de saisie ou cliquez sur le bouton S\*'electionner
le fichier... pour parcourir \*`a la recherche du chemin d'acc\*`es
et du nom de fichier.
 Pour imprimer directement les sections sur une imprimante, cliquez sur
le bouton de radio Imprimer sur l'imprimante.
 Pour obtenir un compl\*'ement d'information, voir 
Sp\*'ecifier la destination de l'impression.
.IP \(rh
 Cliquez sur Imprimer pour imprimer les sections s\*'electionn\*'ees.
 Pour imprimer rapidement plusieurs sections \*`a partir de la fen\*^etre
Liste des livres (c'est-\*`a-dire sans utiliser la bo\*^ite de dialogue
Imprimer):
.IP \(rh
 S\*'electionnez les sections \*`a imprimer, de la
mani\*`ere d\*'ecrite ci-dessus.
.IP \(rh
 Cliquez sur le bouton Imprimer ou choisissez Imprimer sur
le menu Fichier. Le Gestionnaire des informations imprime la section sans
afficher la bo\*^ite de dialogue Imprimer.
.NH 1 
Sp\*'ecifier la ou les sections \*`a
imprimer
.PP
 Le Gestionnaire des informations permet de sp\*'ecifier si vous
souhaitez imprimer une seule section, un nombre de sections non contigu\:es,
un groupe de sections ou des sections connexes. Pour ce faire, utilisez la
zone A imprimer de la bo\*^ite de dialogue Imprimer.
 Pour sp\*'ecifier que vous souhaitez imprimer une seule section
ou plusieurs sections non contigu\:es (option disponible lorsque vous invoquez
la fonction d'impression \*`a partir de la Liste de livres), cliquez sur
le bouton de radio Sections.
 Pour imprimer une section et ses sections subalternes, cliquez sur le
bouton de radio Hi\*'erarchie.
*
.FS
* 
 Lorsque vous cliquez sur Hi\*'erarchie, la zone Nombre de sections
de la bo\*^ite de dialogue Imprimer est actualis\*'ee de mani\*`ere
\*`a indiquer le nombre de sections incluses dans cette hi\*'erarchie.
.FE
 
.NH 1 
Sp\*'ecifier la destination de l'impression
.XS
imprimer
.XE
.XS
dans un fichier
.XE
.PP
 Vous pouvez envoyer directement des sections ou des livres s\*'electionn\*'es
\*`a une imprimante, ou enregistrer les sections dans un fichier PostScript
\*`a imprimer ult\*'erieurement.
.NH 2 
Imprimer directement sur une imprimante
.PP
 Pour imprimer directement sur une imprimante:
.IP \(rh
 Cliquez sur le bouton de radio Imprimante.
 La zone de saisie Imprimante sontient le <comment>V\*'erifier comment
cela appara\*^it dans l'interface...</comment>X Printer Specifier de l'imprimante
\*`a utiliser pour la t\*^ache d'impression. Le <comment>V\*'erifier
comment cela appara\*^it dans l'interface...</comment>X Printer Specifier
est un identificateur qui d\*'esigne une et une seule imprimante <comment>
V\*'erifier comment cela appara\*^it dans l'interface...</comment>X
Printer. Le format de cet identificateur est le suivant:
.CW
 \fI printerName\fR @\fI host\fR : \fI display\fR .\fI screen\fR 
.R
 
 La partie .\fI screen\fR  de cette syntaxe est facultative.
.IP \(rh
 Utilisez l'imprimante dont le nom est affich\*'e, ou s\*'electionnez
une autre imprimante en cliquant sur le bouton S\*'electionner l'imprimante...
et en utilisant la bo\*^ite de dialogue de s\*'election d'imprimante.
.NH 2 
Imprimer dans un fichier
.PP
 Pour imprimer dans un fichier:
.IP \(rh
 Cliquez sur le bouton de radio Imprimer dans le fichier.
.IP \(rh
 Tapez le nom du fichier destin\*'e \*`a recevoir la
sortie PostScript. Vous pouvez \*'egalement s\*'electionner les r\*'epertoire
et fichier en cliquant sur le bouton <comment>Traduire/v\*'erifier dans
l'interface...</comment>S\*'electionner le fichier<?Pub Caret>... et en
utilisant la bo\*^ite de dialogue de s\*'election de fichier.
.bp
<?Pub *0000016827>
\" <!-- $XConsortium: ch08.sgm /main/3 1996/12/20 20:00:08 rws $ -->
\" <!-- (c) Copyright 1996 Digital Equipment Corporation. -->
\" <!-- (c) Copyright 1996 Hewlett-Packard Company. -->
\" <!-- (c) Copyright 1996 International Business Machines Corp. -->
\" <!-- (c) Copyright 1996 Sun Microsystems, Inc. -->
\" <!-- (c) Copyright 1996 Novell, Inc. -->
\" <!-- (c) Copyright 1996 FUJITSU LIMITED. -->
\" <!-- (c) Copyright 1996 Hitachi. -->
.TL
 Personnaliser le Gestionnaire des informations
.XS
pr\*'ef\*'erences
.XE
.XS
configurer
.XE
.XS
Gestionnaire des informations
.XE
.XS
personnaliser
.XE
.LP
 Vous pouvez modifier certains aspects de plusieurs fonctionnalit\*'es
du Gestionnaire des informations, dont vos pr\*'ef\*'erences pour
les fonctions suivantes:
.IP "Explorateur"
 Vous pouvez sp\*'ecifier la taille par d\*'efaut de la police,
la g\*'eom\*'etrie et l'\*'etat d'ancrage de la fen\*^etre
de lecture. Voir Configurer des pr\*'ef\*'erences d'exploration.
.IP "Carte"
 Vous pouvez d\*'eterminer la g\*'eom\*'etrie par d\*'efaut
de la carte et si la carte g\*'eographique est actualis\*'ee automatiquement
\*`a mesure de vos d\*'eplacements dans la biblioth\*`eque d'informations.
Voir Configurer des pr\*'ef\*'erences de .
.IP "Historique"
 D\*'eterminez le nombre maximal de titres de section inclus dans
les listes Historique des sections et Historique des recherches. Voir 
role="JumpText" Configurer les historiques.
.IP "Recherche"
 Indiquez le maximum de titres de section \*`a inclure dans les listes
R\*'esultats de la recherche et si la premi\*`ere concordance (ou \fI r\*'eponse pertinente\fR ) est affich\*'ee automatiquement
dans une fen\*^etre de lecture. Voir Modifier les pr\*'ef\*'erences de.
 Pour changer un de ces attributs, choisissez Pr\*'ef\*'erences
sur le menu Options d'une fen\*^etre de lecture quelconque. Le Gestionnaire
des informations ouvre la fen\*^etre Pr\*'ef\*'erences comme l'indique
la figure suivante.
.XS
Pr\*'ef\*'erences, fen\*^etre
.XE
.XS
exemple
.XE
La fen\*^etre Pr\*'ef\*'erences
.PSPIC "./graphics/mappref.eps"
*
.FS
* 
 Pour maintenir les pr\*'ef\*'erences en vigueur lors de l'ouverture
initiale de la fen\*^etre Pr\*'ef\*'erences, cliquez sur <comment>
Je d\*'eteste \*Q Restaurer\*U  mais enfin on a pas le choix</comment>Restaurer
avant de refermer la fen\*^etre Pr\*'ef\*'erences.
.FE
 
.NH 1 
Configurer des pr\*'ef\*'erences d'exploration
.XS
parcourir
.XE
.XS
d\*'efinir des pr\*'ef\*'erences
d'exploration
.XE
.XS
Explorateur
.XE
.XS
d\*'efinir des pr\*'ef\*'erences
.XE
.XS
pr\*'ef\*'erences
.XE
.XS
parcourir
.XE
.PP
 Vous pouvez modifier les comportements par d\*'efaut suivants de
l'explorateur:
.IP -
 G\*'eom\*'etrie de l'explorateur. Voir 
Modifier la g\*'eom\*'etrie de l'explorateur.
.IP -
 Echelle de la police. Voir Modifier l'\*'etat d'ancrage de la fen\*^etre.
.IP -
 Etat d'ancrage de la fen\*^etre. Voir 
Configurer des pr\*'ef\*'erences de .
 Pour ouvrir la fen\*^etre Pr\*'ef\*'erences d'exploration,
s\*'electionner Explorer sur la zone de liste d\*'eroulante des pr\*'ef\*'erences.
 La figure suivante repr\*'esente les Pr&eacute;f&eacute;rences
d'exploration.
Pr\*'ef\*'erences d'exploration
.PSPIC "./graphics/prefwin.eps"
.NH 2 
Modifier la g\*'eom\*'etrie de l'explorateur
.XS
pr\*'ef\*'erences
.XE
.XS
taille de la fen\*^etre
de lecture
.XE
.XS
fen\*^etre de lecture
.XE
.XS
d\*'efinir une taille par d\*'efaut
.XE
.PP
 Vous pouvez augmenter ou r\*'eduire la taille par d\*'efaut
des fen\*^etres de lecture du Gestionnaire des informations en modifiant
la valeur du champ G\*'eom\*'etrie de l'explorateur. La taille par
d\*'efaut est de 500x630 pixels.
 Pour modifier la taille par d\*'efaut de la fen\*^etre de lecture
:
.IP \(rh
 A l'aide de la fonction de dimensionnement du gestionnaire
de fen\*^etres, ajustez une fen\*^etre \*`a la taille que vous souhaitez
utiliser par d\*'efaut.
.IP \(rh
 Cliquez sur la case \*`a droite du champ G\*'eom\*'etrie
de l'explorateur. Le Gestionnaire des informations affiche un message sur
la mani\*`ere de d\*'efinir la taille par d\*'efaut.
.IP \(rh
 Cliquez \*`a l'int\*'erieur de la taille \*`a
utiliser par d\*'efaut pour la fen\*^etre de lecture. Le Gestionnaire
des informations ins\*`ere les coordonn\*'ees de la fen\*^etre
dans le champ G\*'eom\*'etrie de l'explorateur.
.IP \(rh
 Cliquez sur OK pour appliquer la modification et refermer
la fen\*^etre Pr\*'ef\*'erences. Les nouvelles fen\*^etres de
lecture adopteront la taille sp\*'ecifi\*'ee.
*
.FS
* 
 Si vous modifiez la taille par d\*'efaut de la fen\*^etre de
lecture, les fen\*^etres de lecture existantes ne sont pas redimensionn\*'ees.
.FE
 
.NH 2 
Modifier l'\*'echelle de la police
.XS
pr\*'ef\*'erences
.XE
.XS
fen\*^etre de lecture,
taille de la police
.XE
.XS
fen\*^etre
de lecture
.XE
.XS
sp\*'ecifier la taille par d\*'efaut
de la police
.XE
.PP
 Vous pouvez augmenter ou r\*'eduire la taille de la police du texte
affich\*'e dans la fen\*^etre de lecture. Pour sp\*'ecifier une
taille de police diff\*'erente, cliquez sur la Fl\*`eche vers le haut
pour augmenter l'\*'echelle de la police, ou sur la Fl\*`eche vers
le bas pour la r\*'eduire.
 Cliquez sur OK pour valider la modification et refermez la fen\*^etre
Pr\*'ef\*'erences. Le Gestionnaire des informations modifie le texte
de toutes les sections actuellement affich\*'ees de mani\*`ere \*`a
refl\*'eter la nouvelle \*'echelle de police. Toute nouvelle fen\*^etre
de lecture ouverte affichera adoptera \*'egalement cette nouvelle taille
de police.
*
.FS
* 
 La modification de l'\*'echelle de la police peut affecter le renvoi
automatique \*`a la ligne de la section. Pour visualiser les effets de
la modification d'\*'echelle de police, cliquez sur Appliquer sans refermer
la fen\*^etre Pr\*'ef\*'erences.
.FE
 
.NH 2 
Modifier l'\*'etat d'ancrage de la fen\*^etre
.XS
fen\*^etre de lecture
.XE
.XS
\*'etat d'ancrage
par d\*'efaut
.XE
.XS
ancrage
.XE
.XS
\*'etat par d\*'efaut
.XE
.XS
pr\*'ef\*'erences
.XE
.XS
\*'etat d'ancrage
de la fen\*^etre
.XE
.PP
 Vous pouvez d\*'eterminer si les fen\*^etres de lecture sont
ancr\*'ees automatiquement ou pas. Par d\*'efaut, le Gestionnaire
des informations n'ancre pas automatiquement les fen\*^etres de lecture.
Cependant, si une fen\*^etre de lecture n'est pas ancr\*'ee, son contenu
est remplac\*'e chaque fois que vous passez \*`a une autre section.
 Si vous ancrez fr\*'equemment des fen\*^etres de lecture de mani\*`ere
\*`a ouvrir simultan\*'ement plusieurs sections dans des fen\*^etres
diff\*'erentes, configurez des pr\*'ef\*'erences indiquant l'ancrage
automatiquement des fen\*^etres de lecture lors de leur ouverture. Pour
ce faire, cliquez sur la case \*`a cocher Ancrer la fen\*^etre, puis
sur Appliquer.
.NH 1 
Configurer des pr\*'ef\*'erences de <comment>
Dans la liste de termes fournie par Karin, il y a \*Q Carte Graphique\*U .
Il n'est pas n\*'ecessaire de mettre une majuscule \*`a Graphique.
</comment>carte graphique
.XS
pr\*'ef\*'erences
.XE
.XS
carte graphique
.XE
.XS
carte
graphique
.XE
.XS
d\*'efinir des pr\*'ef\*'erences
.XE
.PP
 Vous pouvez modifier les attributs par d\*'efaut suivants de la
carte graphique:
.IP -
 G\*'eom\*'etrie de la carte. Voir 
Modifier la g\*'eom\*'etrie de la.
.IP -
 Mise \*`a jour automatique. Voir 
Configurer la mise \*`a jour automatique.
 Pour afficher la fen\*^etre Pr\*'ef\*'erences de carte, s\*'electionnez
Carte sur la zone de liste d\*'eroulante Pr\*'ef\*'erences de.
 La figure suivante repr\*'esente la fen\*^etre Pr\*'ef\*'erences
de carte.
Pr\*'ef\*'erences de carte
.PSPIC "./graphics/mappref.eps"
.NH 2 
Modifier la g\*'eom\*'etrie de la
carte
.XS
pr\*'ef\*'erences
.XE
.XS
taille
de la carte
.XE
.XS
carte graphique
.XE
.XS
d\*'efinir la taille par d\*'efaut
.XE
.PP
 Vous pouvez augmenter ou r\*'eduire la taille de la carte graphique
en modifiant la valeur du champ G\*'eom\*'etrie de la carte. La taille
par d\*'efaut est de 520x350 pixels.
 Pour modifier cette taille:
.IP \(rh
 Cliquez sur la case \*`a droite du champ G\*'eom\*'etrie
de la carte. L'explorateur affiche un message expliquant comment modifier
la taille par d\*'efaut.
.IP \(rh
 Cliquez sur la fen\*^etre de la taille \*`a adopter
par d\*'efaut pour la carte graphique. Le Gestionnaire des informations
ins\*`ere les coordonn\*'ees appropri\*'ees dans le champ G\*'eom\*'etrie
de la carte.
.IP \(rh
 Cliquez sur OK pour valider les modifications et refermer
la fen\*^etre Pr\*'ef\*'erences.
 A la prochaine initialisation du Gestionnaire des informations, la taille
par d\*'efaut de la carte graphique refl\*'etera la modification apport\*'ee.
.NH 2 
Configurer la mise \*`a jour automatique
.XS
carte graphique
.XE
.XS
configurer la mise \*`a jour
automatique par d\*'efaut
.XE
.XS
pr\*'ef\*'erences
.XE
.XS
\*'etat de mise \*`a
jour automatique de la carte
.XE
.PP
 Vous avez la possibilit\*'e de sp\*'ecifier si le Gestionnaire
des informations met automatiquement \*`a jour la carte graphique de mani\*`ere
\*`a refl\*'eter la section en cours de lecture dans la fen\*^etre
de lecture active.
 Pour indiquer au Gestionnaire des informations de mettre automatiquement
la carte graphique \*`a jour:
.IP \(rh
 Faites basculer le bouton Mise \*`a jour automatique sur
le r\*'eglage de votre choix.
.IP \(rh
 Cliquez sur Appliquer.
.NH 1 
Configurer les historiques
.XS
pr\*'ef\*'erences
.XE
.XS
historiques
.XE
.XS
historiques
.XE
.XS
d\*'efinir des valeurs par d\*'efaut
.XE
.PP
 Il se peut que vous n'utilisiez jamais la plupart des entr\*'ees
incluses dans les listes Historique des sections et Historique des recherches
et que vous pr\*'ef\*'eriez par cons\*'equent limiter la longueur
de ces listes. Vous pouvez modifier le nombre maximal de sections incluses
dans:
.IP -
 Liste Historique des sections. Voir 
Modifier la liste Historique des sections.
.IP -
 Liste Historique des recherches. Voir 
Modifier la liste Historique des recherches.
 Pour afficher la fen\*^etre Pr\*'ef\*'erences d'historique,
s\*'electionnez Historique sur la zone de liste d\*'eroulante Pr\*'ef\*'erences
de.
 La figure suivante repr\*'esente la fen\*^etre Pr\*'ef\*'erences
d'historique.
Pr\*'ef\*'erences d'historique
.PSPIC "./graphics/histpref.eps"
.NH 2 
Modifier la liste Historique des sections
.XS
pr\*'ef\*'erences
.XE
.XS
taille de la liste
Hostorique des sections
.XE
.XS
Historique
des sections, liste
.XE
.XS
d\*'efinir la taille par d\*'efaut
.XE
.PP
 Vous pouvez modifier le nombre maximal de titres de section maintenus
par le Gestionnaire des informations dans la liste Historique des sections.
La valeur par d\*'efaut est 100 sections.
 Pour modifier le nombre maximal de sections dans la liste Historique
des sections, cliquez sur la fl\*`eche vers le haut pour augmenter le
nombre ou la fl\*`eche vers le bas pour le r\*'eduire.
 Cliquez sur OK pour appliquer la modification et refermer la fen\*^etre
Pr\*'ef\*'erences. Le Gestionnaire des informations limite la liste
Historique des sections au nombre des sections sp\*'ecifi\*'e.
.NH 2 
Modifier la liste Historique des recherches
.XS
pr\*'ef\*'erences
.XE
.XS
liste Historique des
recherches
.XE
.XS
Historique des recherches,
liste
.XE
.XS
d\*'efinir la taille par d\*'efaut
.XE
.PP
 Vous pouvez modifier le nombre maximal de titres de section maintenus
par le Gestionnaire des informations dans la liste Historique des recherches.
La valeur par d\*'efaut est de 50 sections.
 Pour modifier le nombre maximal de sections dans la liste Historique
des recherches, cliquez sur la fl\*`eche vers le haut pour augmenter le
nombre ou la fl\*`eche vers le bas pour le r\*'eduire.
 Cliquez sur OK pour appliquer la modification et refermer la fen\*^etre
Pr\*'ef\*'erences. Le Gestionnaire des informations limite la liste
Historique des recherches au nombre de sections sp\*'ecifi\*'e.
.NH 1 
Modifier les pr\*'ef\*'erences de
recherche
.XS
pr\*'ef\*'erences
.XE
.XS
recherche
.XE
.XS
rechercher
.XE
.XS
d\*'efinir des pr\*'ef\*'erences
.XE
.PP
 Vous pouvez d\*'efinir les pr\*'ef\*'erences de recherche
suivantes:
.IP -
 Maximum de correspondances. Voir D\*'efinir le maximum de correspondances.
.IP -
 Affichage automatique de la premi\*`ere correspondance.
Voir Configurer l'affichage automatique de la.
 Pour afficher la fen\*^etre Pr\*'ef\*'erences de recherche,
s\*'electionnez Recherche sur la zone de liste d\*'eroulante Pr\*'ef\*'erences
de.
 La figure suivante repr\*'esente la fen\*^etre Pr\*'ef\*'erences
de recherche.
Pr\*'ef\*'erences de recherche
.PSPIC "./graphics/serchprf.eps"
.NH 2 
D\*'efinir le maximum de correspondances
.XS
rechercher
.XE
.XS
d\*'efinir le maximum de correspondances
par d\*'efaut
.XE
.XS
pr\*'ef\*'erences
.XE
.XS
d\*'efinir le maximum de correspondances par d\*'efaut
.XE
.PP
 Vous trouvez peut-\*^etre que la liste de recherche renvoie<?Pub Caret> trop
de correspondances (ou \fI r\*'eponses\fR ). Pour raccourcir
ces listes, vous pouvez modifier le nombre maximal de titres de section affich\*'es
dans la liste R\*'esultats de la recherche. La valeur par d\*'efaut
est de 50 sections.
 Pour modifier le maximum de sections dans la liste R\*'esultats
de la recherche, cliquez sur la fl\*`eche vers le haut pour l'augmenter
ou sur la fl\*`eche vers le bas pour r\*'eduire ce nombre.
 Cliquez sur OK pour valider la modification et refermer la fen\*^etre
Pr\*'ef\*'erences. Le Gestionnaire des informations limite la liste
R\*'esultats de la recherche au nombre de sections ainsi indiqu\*'e.
.NH 2 
Configurer l'affichage automatique de la
premi\*`ere correspondance
.XS
pr\*'ef\*'erences
.XE
.XS
configurer l'affichage automatique par d\*'efaut
de la premi\*`ere correspondance
.XE
.XS
rechercher
.XE
.XS
configurer l'affichage automatique par d\*'efaut
de la premi\*`ere correspondance
.XE
.PP
 Pour afficher automatiquement la premi\*`ere section contenant des
correspondances (ou \fI r\*'eponses pertinentes\fR ) significatives,
utilisez la fen\*^etre Pr\*'ef\*'erences pour configurer la fonctionnalit\*'e
Affichage automatique de la premi\*`ere correspondance. Cliquez sur le
bouton Affichage automatique de la premi\*`ere correspondance pour indiquer
au Gestionnaire des informations d'activer ou de d\*'esactiver cette fonctionnalit\*'e.
Cliquez sur OK pour appliquer la modification et refermer la fen\*^etre
Pr\*'ef\*'erences.
.bp
<?Pub *0000023793>
\" <!-- $XConsortium: glossary.sgm /main/2 1996/12/17 15:37:05 rws $ -->
\" <!-- (c) Copyright 1996 Digital Equipment Corporation. -->
\" <!-- (c) Copyright 1996 Hewlett-Packard Company. -->
\" <!-- (c) Copyright 1996 International Business Machines Corp. -->
\" <!-- (c) Copyright 1996 Sun Microsystems, Inc. -->
\" <!-- (c) Copyright 1996 Novell, Inc. -->
\" <!-- (c) Copyright 1996 FUJITSU LIMITED. -->
\" <!-- (c) Copyright 1996 Hitachi. -->
.TL
 Glossaire
.LP
<comment>J'ai remis le Glossaire dans l'ordre alphab\*'etique fran\*,cais.
Certains de ces termes figurent d\*'ej\*`a dans les glossaires du
User Guide et du System Manager Guide, et doivent donc correspondre. Attention
surtout \*`a \*Q infolib\*U . Dans les autres manuels nous avons
laiss\*'e \*Q infolib\*U  (et pas \*Q biblinfo\*U ).</comment>
.IP "Aller<comment>et pas \*Q Go\*U </comment>"
 Fen\*^etre de lecture: menu Aller. Utilisez ce menu pour naviguer
dans l'ordre des sections d'une biblioth\*`eque d'informations ou pour
revenir aux sections d\*'ej\*`a lues.
.IP "biblioth\*`eque d'informations"
 Une collection de rayons, dans laquelle chaque rayon contient une collection
de livres, et chaque livre contient des sections.
.IP "Bo\*^ite \*`a outils du d\*'eveloppeur du
syst\*`eme d'information</glossterm>
 La panoplie d'outils et d'interfaces de programmation d'applications
(API) qui permettent aux auteurs du syst\*`eme d'information de r\*'ediger,
de traiter et de consulter les biblioth\*`eques d'informations.
.IP "carte graphique"
 Repr\*'esentation visuelle de la structure interne d'un livre, selon
laquelle les titres de section du livre sont affich\*'es sous forme d'une
"arborescence" graphique.
.IP "case panoramique"
 Zone d'affichage panoramique bi-dimensionnelle dans une carte graphique
du Gestionnaire des informations. Cette zone vous permet de faire d\*'efiler
la partie visible de la carte dans la fen\*^etre invisible (et, ce faisant,
de r\*'ev\*'eler la partie pr\*'ealablement masqu\*'ee).
.IP "Configuration de l'impression"
 Bo\*^ite de dialogue qui permet de sp\*'ecifier des param\*`etres
d'impression pour l'imprimante actuellement s\*'electionn\*'ee, tels
que l'orientation de la page (portrait ou paysage), l'impression recto ou
rectoverso, le bac \*`a papier \*`a utiliser. Cette bo\*^ite de
dialogue s'affiche \*`a partir de l'Agenda, du Gestionnaire des informations,
de la Bo\*^ite aux lettres<comment>Mailer</comment> et de l'Editeur de
texte lorsque vous cliquez deux fois sur le bouton Configurer de leurs bo\*^ites
de dialogue d'impression respectives.
.IP "connexion, bouton de"
 Editeur de requ\*^etes. Utilisez ce bouton pour inclure un autre
terme dans une recherche.
.IP "Cr\*'eer une note"
 Fen\*^etre de lecture: menu Rep\*`eres. Utilisez cette option
pour cr\*'eer un signet annot\*'e au sein d'une section dans une fen\*^etre
de lecture active.
.IP "Cr\*'eer un signet"
 Fen\*^etre de lecture: menu Rep\*`eres. Utilisez cette option
pour cr\*'eer un signet vierge au sein d'une section dans une fen\*^etre
de lecture active.
.IP "D\*'etacher le graphique"
 Utilisez cet \*'el\*'ement de menu pour copier une image graphique
s\*'electionn\*'ee dans une fen\*^etre s\*'epar\*'ee nomm\*'ee \fI fen\*^etre Graphique d\*'etach\*'e\fR .
.IP "Editeur d'\*'etendues de recherche"
 La bo\*^ite de dialogue qui vous permet de cr\*'eer des \*'etendues
de recherche personnalis\*'ees.
.IP "Editeur de requ\*^etes"
 La bo\*^ite de dialogue qui vous permet de d\*'efinir des recherches
d\*'etaill\*'ees dans une biblioth\*`eque d'informations.
.IP "Editeur de signets"
 La bo\*^ite de dialogue qui appara\*^it lorsque vous cliquez deux
fois sur une ic\*^one de signet dans une fen\*^etre de lecture. Utilisez
cet \*'editeur pour afficher et modifier des notes et des signets existants.
.IP "\*'etendue de la recherche"
 L'\*'etendue des livres et des types d'information \*`a laquelle
s'appliquera une recherche du Gestionnaire des informations.
.IP "explorer<comment>ou \*Q parcourir\*U , mais vous
avez mis Explorateur pour Browser</comment></glossterm>
 1) Parcourir une collection, telle qu'une base de donn\*'ees, une
vue du Gestionnaire de fichiers, une zone de liste ou un fichier texte, \*`a
la recherche soit d'un \*'el\*'ement sp\*'ecifique, soit d'un
\*'el\*'ement int\*'eressant quelconque. Implique g\*'en\*'eralement
que vous observez les informations sans n\*'ecessairement les changer.
 2) Rechercher en parcourant et en faisant d\*'efiler des \*'ecrans
ou fen\*^etres de donn\*'ees.
.IP "fen\*^etre ancr\*'ee"
 Une fen\*^etre de lecture configur\*'ee de mani\*`ere \*`a
ce que le texte affich\*'e dans la fen\*^etre soit conserv\*'e
lorsque vous suivez un lien et ouvrez une fen\*^etre pour le nouveau texte.
Si la fen\*^etre n'est pas ancr\*'ee, le Gestionnaire des informations
actualise le texte de la fen\*^etre de lecture en cours chaque fois que
vous suivez un lien.
.IP "fen\*^etre de lecture"
 Fen\*^etre du Gestionnaire des informations qui affiche le texte,
les tables et les graphiques d'une section sp\*'ecifique dans un livre.
.IP "Gestionnaire des informations"
 L'application logicielle qui vous permet de parcourir et de faire des
recherches dans des collections de documentation en ligne appel\*'ees
des \fI biblioth\*`eques d'informations\fR .
.IP "Graphique d\*'etach\*'e, ic\*^one"
 Une ic\*^one indiquant l'endroit d'o\*`u un graphique a \*'et\*'e
d\*'etach\*'e.
.IP "Graphique d\*'etach\*'e, fen\*^etre"
 La fen\*^etre de bo\*^ite de dialogue qui appara\*^it lorsque
vous d\*'etachez un graphique.
.IP "Historique automatique"
 Fen\*^etre Liste de livres: menu Options. Utilisez cette fonctionnalit\*'e
pour d\*'eterminer si le Gestionnaire des informations indique ou non
o\*`u vous trouvez dans la hi\*'erarchie de la biblioth\*`eque
d'informations.
.IP "infolib<comment>et pas \*Q biblinfo\*U . Attention
aussi \*`a l'option \*Q Load infolib\*U  \(em Je ne sais pas
ce que vous avez mis dans l'interface.</comment></glossterm>
 L'ensemble des fichiers, y compris les instances SGML, les graphiques
et les index, qui constituent une biblioth\*`eque d'informations. Voir \fI information library\fR .
.IP "information"
 Voir \fI Gestionnaire des informations\fR .
.IP "lien"
 Une r\*'ef\*'erence hypertexte \*`a un point d'implantation.
Le contenu d'un lien repr\*'esente une zone active du Gestionnaire des
informations. Voir \fI point d'implantation\fR .
.IP "liste de livres"
 La liste de rayons de biblioth\*`eque et de livres disponibles aupr\*`es
du Gestionnaire des informations.
.IP "Liste de livres, fen\*^etre"
 La bo\*^ite de dialogue du Gestionnaire des informations qui permet
d'acc\*'eder aux informations m\*'emoris\*'ees dans une biblioth\*`eque
d'informations afin de les afficher en ligne ou de les imprimer.
.IP "Lister les rep\*`eres"
 Fen\*^etre de lecture: menu Rep\*`eres<comment>\*Q Marks\*U 
menu</comment>. Utilisez ce menu pour lister tous vos signets vierges et annot\*'es.
.IP "livre"
 Un livre \*'electronique. Voir aussi \fI rayon\fR 
et \fI biblioth\*`eque d'informations\fR .
.IP "objet de commande du Tableau de bord"
 Objet du Tableau de bord utilis\*'e comme interface avec les services
syst\*`eme de base et les t\*^aches et op\*'erations fr\*'equemment
effectu\*'ees. Utilisez le nom sp\*'ecifique de l'objet de commande
dans les cas appropri\*'es. Les objets de commande dans le Tableau de
bord distribu\*'e par d\*'efaut sont les suivants: Horloge, Agenda,
Gestionnaire de fichiers, Editeur de texte, Bo\*^ite aux lettres, Imprimante,
Gestionnaire de styles, Gestionnaire d'applications, Gestionnaire des informations
et Corbeille.
.IP "point d'implantation"
 Dans un document, point d'ancrage auquel les liens hypertexte peuvent
faire r\*'ef\*'erence. Chaque point d'implantation est associ\*'e
\*`a un identificateur unique dans toute la biblioth\*`eque d'informations.
.IP "rayon"
 Groupe de livres \*'electroniques sur des sujets connexes, regroup\*'es
dans un \*Q rayon\*U <comment>bookcase</comment>. Un ensemble logique
d'informations (le cas \*'ech\*'eant, plusieurs livres connexes) accompagn\*'e
d'un seul index avec capacit\*'es de recherche textuelle. Un rayon (de
biblioth\*`eque) et les feuilles de style repr\*'esentent la collection
minimale de donn\*'ees pouvant \*^etre \*'elabor\*'ee sous
forme de biblioth\*`eque d'informations. Voir aussi \fI biblioth\*`eque
d'informations\fR .
.IP "rayon, DTD de"
 La d\*'efinition de type de document (DTD) qui d\*'etermine
la structure des fichiers de sp\*'ecifications utilis\*'es pour cr\*'eer
des livres pour le Gestionnaire des informations. Voir aussi \fI d\*'efinition
de type de document\fR .
.IP "rayon, sp\*'ecification de"
 Un document SGML,<?Pub Caret> qui contient ou sp\*'ecifie les fichiers
de livre, les feuilles de style et autres entit\*'es SGML n\*'ecessaires
\*`a l'\*'elaboration d'une biblioth\*`eque d'informations.
.IP "Rep\*`eres"
 Fen\*^etre de lecture: menu Rep\*`eres. Utilisez ce menu pour
cr\*'eer, \*'editer et supprimer des signets.
.IP "R\*'esultats de la recherche, fen\*^etre"
 Fen\*^etre qui affiche la liste des sections contenant des correspondances.
Le Gestionnaire des informations affiche une fen\*^etre R\*'esultats
de la recherche d\*`es qu'une recherche s'ach\*`eve.
.IP "section"
 Une unit\*'e unique de documentation affich\*'ee dans une fen\*^etre
de lecture du Gestionnaire des informations.
.IP "signet"
 Un rep\*`ere du Gestionnaire des informations que les utilisateurs
peuvent cr\*'eer pour annoter un passage de texte ou un \*'el\*'ement
graphique sp\*'ecifique dans une biblioth\*`eque d'informations. Le
Gestionnaire des informations repr\*'esente un signet par une ic\*^one
dans la marge gauche d'une fen\*^etre de lecture.
.IP "syst\*`eme d'information"
 Constitu\*'e des biblioth\*`eques d'informations (les donn\*'ees),
du Gestionnaire des informations (l'afficheur) et de la Bo\*^ite \*`a
outils du d\*'eveloppeur du syst\*`eme d'information (les utilitaires
de d\*'eveloppement).
.IP "table des mati\*`eres hypertexte"
 Une liste hi\*'erarchique hypertexte des titres de section. Les
tables des mati\*`eres hypertexte structurent les diverses sections des
livres en ligne au sein du syst\*`eme d'information.
.IP "Visualiser"
 Ic\*^one et \*'el\*'ement de menu permettant d'ouvrir une
fen\*^etre de lecture destin\*'ee \*`a une section s\*'electionn\*'ee.
.bp
\" <!--fickle 1.14 mif-to-docbook 1.7 01/02/96 10:57:19-->
<?Pub *0000018056>
